# Project
maven_group=io.github.magistu
release_channel=release

# Common
minecraft_version=1.20.1
display_minecraft_version=1.20.x
minecraft_min_version=1.20
minecraft_max_version=1.21
enabled_platforms=fabric,forge

# Mod properties
mod_version=2.6
mod_name=EpicKnightsAddon
mod_display_name=Epic Knights: Addon
mod_title=Epic Knights: Addon
mod_id=magistuarmoryaddon
mod_license=All Rights Reserved
mod_authors=Magistu, SuperSus890, SteveMe, itzme1on, Desperate_bork, minucius, hoetistic, theblackchimera, Santusio, Flavius_Blue, caballerohospitalario, alhendahu, Reymecos, Skydog
mod_contributors=archimedes
mod_description=Adds medieval stuff to the game
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/epic-knights-addon
mod_issues_url=https://github.com/Magistu/Epic-Knights-Addon/issues
mod_git_url=https://github.com/Magistu/Epic-Knights-Addon
mod_discord_url=https://discord.gg/R8U8Hpgr75
mod_curseforge_id=925866
mod_modrinth_id=txMuoRai

# Other mods
cloth_config_version=11.0.99
architectury_version=9.0.8
fabric_loader_version=0.14.21
fabric_api_version=0.84.0+1.20.1
forge_version=47.4.0
forge_version_range=[47,)
epic_fight_version=20.13.6
epic_knights_version=10.8

# Gradle
org.gradle.jvmargs=-Xmx4G