# Project
maven_group                     = io.github.magistu
release_channel                 = release

# Common
minecraft_version               = 1.21.1
display_minecraft_version       = 1.21.1
minecraft_min_version           = 1.21
minecraft_max_version           = 1.21.2
enabled_platforms               = fabric,neoforge

# Fabric
fabric_loader_version           = 0.17.2
min_fabric_loader_version       = 0.16
fabric_api_version              = 0.104.0+1.21.1

# NeoForge
neoforge_version                = 21.1.54
neoforge_version_range          = [21,)
neoforge_loader_version_range   = [2,)

# Mod options
mod_version                     = 1.24
mod_id                          = magistuarmoryaddon
mod_display_name                = Epic Knights: Addon
mod_authors                     = Magistu, SuperSus890, SteveMe, itzme1on, Desperate_bork, minucius, hoetistic, theblackchimera, Santusio, Flavius_Blue, caballerohospitalario, alhendahu, Reymecos, Skydog
mod_contributors                = archimedes
mod_description                 = Adds medieval stuff to the game
mod_license                     = All Rights Reserved
mod_page_url                    = https://www.curseforge.com/minecraft/mc-mods/epic-knights-addon
mod_issues_url                  = https://github.com/Magistu/Epic-Knights-Addon/issues
mod_git_url                     = https://github.com/Magistu/Epic-Knights-Addon
mod_discord_url                 = https://discord.gg/H9CVcXEmYe
mod_curseforge_id               = 925866
mod_modrinth_id                 = txMuoRai

# Dependencies
architectury_api_version        = 13.0.8
cloth_config_version            = 15.0.128
epic_knights_version            = 9.26

# Done to increase the memory available to Gradle.
org.gradle.jvmargs              = -Xmx4G