package com.magistuarmory.addon.item.armor;

import com.magistuarmory.addon.EpicKnightsAddon;
import com.magistuarmory.addon.config.ArmorConfig;
import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;

import java.util.function.Supplier;

public class AddonArmorTypes
{
	public static final ArmorConfig ARMOR_CONFIG = EpicKnightsAddon.CONFIG.armor;

	public static final ArmorType DARK_KNIGHT;
	public static final ArmorType DARK_ARMET;
	public static final ArmorType DARK_STECHHELM;
	public static final ArmorType DARK_JOUSTING;
	public static final ArmorType DARK_SALLET;
	public static final ArmorType DARK_GOTHIC;
	public static final ArmorType DARK_MAXIMILIAN_HELMET;
	public static final ArmorType DARK_MAXIMILIAN;
	public static final ArmorType DARK_GREATHELM;
	public static final ArmorType DARK_CRUSADER;
	public static final ArmorType DARK_GRAND_BASCINET;
	public static final ArmorType DARK_KASTENBRUST;
	public static final ArmorType SAVOYARD_HELMET;
	public static final ArmorType MORION;
	public static final ArmorType PIKEMAN;
	public static final ArmorType MILANESE_ARMET;
	public static final ArmorType BRITISH_ARMET;
	public static final ArmorType AVANT;
	public static final ArmorType VISORED_KETTLEHAT;
	public static final ArmorType CERVELLIERE;
	public static final ArmorType CLOSED_BARBUTE;
	public static final ArmorType BICOQUE;
	public static final ArmorType LINEN;
	public static final ArmorType SALLET_WITHOUT_NECK_PROTECTION;
	public static final ArmorType BELLOWS_MAXIMILIAN_HELMET;
	public static final ArmorType KULAH_KHUD;
	public static final ArmorType CUMAN_CAPTAIN_HELMET;
	public static final ArmorType MIRROR;
	public static final ArmorType SARACEN;
	public static final ArmorType EARLY_GREATHELM;
	public static final ArmorType XIII_CENTURY_KNIGHT;
	public static final ArmorType KLAPPVISOR_BASCINET;
	public static final ArmorType LATE_BASCINET;
	public static final ArmorType LOBSTER_TAILED_HELMET;
	public static final ArmorType CHAPEL;
	public static final ArmorType CHAINED_GAMBESON;
	public static final ArmorType TABLET_HELMET;
	public static final ArmorType LATE_GREATHELM;
	public static final ArmorType BURGUNDIAN_KETTLEHAT;
	public static final ArmorType CLOSED_BURGONET;
	public static final ArmorType HEAVY_CUIRASSIER;
	public static final ArmorType DARK_HEAVY_CUIRASSIER;
	public static final ArmorType LIGHT_BURGONET;
	public static final ArmorType LATE_BURGONET;
	public static final ArmorType DEVILISH_GROTESQUE_MAXIMILIAN_HELMET;
	public static final ArmorType FACIAL_GROTESQUE_MAXIMILIAN_HELMET;
	public static final ArmorType DARK_GILDED_GREENWICH_ARMET;
	public static final ArmorType DARK_GILDED_GREENWICH;
	public static final ArmorType DARK_GREENWICH_ARMET;
	public static final ArmorType DARK_GREENWICH;
	public static final ArmorType LATE_SALLET;
	public static final ArmorType DARK_LATE_SALLET;
	public static final ArmorType STEEL_PUFF_AND_SLASH;
	public static final ArmorType GILDED_STEEL_PUFF_AND_SLASH;
	public static final ArmorType STURMHAUBE;
	public static final ArmorType SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET;
	public static final ArmorType SILVERED_DARK_MAXIMILIAN_HELMET;
	public static final ArmorType SILVERED_DARK_MAXIMILIAN;
	public static final ArmorType GILDED_GRAND_BASCINET;
	public static final ArmorType CEREMONIAL_KASTENBRUST;
	public static final ArmorType GILDED_XIV_CENTURY_KNIGHT;
	public static final ArmorType GALLOWGLASS;
	public static final ArmorType ENGLISH_KNIGHT;
	public static final ArmorType GILDED_HALF_ARMOR;
	public static final ArmorType GILDED_EXQUISITE_MAXIMILIAN_HELMET;
	public static final ArmorType GILDED_MAXIMILIAN_HELMET;
	public static final ArmorType GILDED_MAXIMILIAN;
	public static final ArmorType COAT_OF_PLATES;
	public static final ArmorType SILVERED_DARK_HALF_ARMOR;
	public static final ArmorType GILDED_DARK_SALLET;
	public static final ArmorType GILDED_DARK_GOTHIC;
	public static final ArmorType GILDED_SALLET;
	public static final ArmorType GILDED_GOTHIC;
	public static final ArmorType GILDED_GREENWICH_ARMET;
	public static final ArmorType GILDED_GREENWICH;
	public static final ArmorType GREENWICH_ARMET;
	public static final ArmorType GREENWICH;
	public static final ArmorType LANDSKNECHT_ORANGE_HAT;
	public static final ArmorType LANDSKNECHT_MAGENTA_HAT;
	public static final ArmorType LANDSKNECHT_LIGHT_BLUE_HAT;
	public static final ArmorType LANDSKNECHT_YELLOW_HAT;
	public static final ArmorType LANDSKNECHT_LIME_HAT;
	public static final ArmorType LANDSKNECHT_PINK_HAT;
	public static final ArmorType LANDSKNECHT_GRAY_HAT;
	public static final ArmorType LANDSKNECHT_LIGHT_GRAY_HAT;
	public static final ArmorType LANDSKNECHT_CYAN_HAT;
	public static final ArmorType LANDSKNECHT_PURPLE_HAT;
	public static final ArmorType LANDSKNECHT_BLUE_HAT;
	public static final ArmorType LANDSKNECHT_BROWN_HAT;
	public static final ArmorType LANDSKNECHT_GREEN_HAT;
	public static final ArmorType LANDSKNECHT_RED_HAT;
	public static final ArmorType LANDSKNECHT_BLACK_HAT;
	public static final ArmorType LANDSKNECHT_WHITE_HAT;
	public static final ArmorType ORANGE_PUFF_AND_SLASH;
	public static final ArmorType MAGENTA_PUFF_AND_SLASH;
	public static final ArmorType LIGHT_BLUE_PUFF_AND_SLASH;
	public static final ArmorType YELLOW_PUFF_AND_SLASH;
	public static final ArmorType LIME_PUFF_AND_SLASH;
	public static final ArmorType PINK_PUFF_AND_SLASH;
	public static final ArmorType GRAY_PUFF_AND_SLASH;
	public static final ArmorType LIGHT_GRAY_PUFF_AND_SLASH;
	public static final ArmorType CYAN_PUFF_AND_SLASH;
	public static final ArmorType PURPLE_PUFF_AND_SLASH;
	public static final ArmorType BLUE_PUFF_AND_SLASH;
	public static final ArmorType BROWN_PUFF_AND_SLASH;
	public static final ArmorType GREEN_PUFF_AND_SLASH;
	public static final ArmorType RED_PUFF_AND_SLASH;
	public static final ArmorType BLACK_PUFF_AND_SLASH;
	public static final ArmorType WHITE_PUFF_AND_SLASH;
	public static final ArmorType PUFF_AND_SLASH;
	public static final ArmorType SCALE_HELMET;
	public static final ArmorType CONDOTTIERO_CAP;
	public static final ArmorType SUGARLOAF_HELMET;
	public static final ArmorType GILDED_SUGARLOAF_HELMET;
	public static final ArmorType PATRICIAN_TUHER_HELMET;
	public static final ArmorType LATE_KETTLEHAT;
	public static final ArmorType CLOSE_HELMET;
	public static final ArmorType EXQUISITE_MAXIMILIAN_HELMET;
	public static final ArmorType PROTO_MAXIMILIAN;
	public static final ArmorType DARK_PROTO_MAXIMILIAN;
	public static final ArmorType HEAVY_BRIGANDINE;
	public static final ArmorType GILDED_HEAVY_BRIGANDINE;
	public static final ArmorType DARK_HEAVY_BRIGANDINE;
	public static final ArmorType CABASSET;
	public static final ArmorType GILDED_CABASSET;
	public static final ArmorType EARLY_CABASSET;
	public static final ArmorType DARK_EARLY_CABASSET;
	public static final ArmorType GILDED_EARLY_CABASSET;
	public static final ArmorType STRAW_HAT;
	public static final ArmorType FANCY_HAT;
	public static final ArmorType TUNIC;
	public static final ArmorType EMBOSED_PARADE_BURGONET;
	public static final ArmorType EMBOSED_PARADE;
	public static final ArmorType DARK_GILDED_PARADE_BURGONET;
	public static final ArmorType DARK_GILDED_PARADE;
	public static final ArmorType DOUBLET;
	public static final ArmorType GOLDEN_NECKLACE;
	public static final ArmorType SILVER_NECKLACE;
	public static final ArmorType SILVER_CROSS_NECKLACE;
	public static final ArmorType GOLDEN_CROSS_NECKLACE;
	public static final ArmorType ARTICULATED;
	public static final ArmorType CUMAN_HELMET;
	public static final ArmorType DARKBLUED_GOTHIC;
	public static final ArmorType DARKBLUED_GREENWICH_ARMET;
	public static final ArmorType DARKBLUED_GREENWICH;
	public static final ArmorType DARKBLUED_KASTENBRUST;
	public static final ArmorType DARKBLUED_ARMET;
	public static final ArmorType DARKBLUED_KNIGHT;
	public static final ArmorType DARKBLUED_MAXIMILIAN_HELMET;
	public static final ArmorType DARKBLUED_MAXIMILIAN;
	public static final ArmorType DARKBLUED_SALLET;
	public static final ArmorType ENGRAVED_CLOSE_HELMET;
	public static final ArmorType ENGRAVED;
	public static final ArmorType FOX_GROTESQUE_MAXIMILIAN_HELMET;
	public static final ArmorType FULLY_GILDED_ARMET;
	public static final ArmorType FULLY_GILDED_ARTICULATED;
	public static final ArmorType FULLY_GILDED_GOTHIC;
	public static final ArmorType FULLY_GILDED_GRAND_BASCINET;
	public static final ArmorType FULLY_GILDED_GREENWICH_ARMET;
	public static final ArmorType FULLY_GILDED_GREENWICH;
	public static final ArmorType FULLY_GILDED_GRILLED_HELMET;
	public static final ArmorType FULLY_GILDED_JOUSTING_HELMET;
	public static final ArmorType FULLY_GILDED_JOUSTING;
	public static final ArmorType FULLY_GILDED_KASTENBRUST;
	public static final ArmorType FULLY_GILDED_KNIGHT;
	public static final ArmorType FULLY_GILDED_MAXIMILIAN_HELMET;
	public static final ArmorType FULLY_GILDED_MAXIMILIAN;
	public static final ArmorType FULLY_GILDED_MILANESE_ARMET;
	public static final ArmorType FULLY_GILDED_SALLET;
	public static final ArmorType GILDED_CHAINMAIL;
	public static final ArmorType GILDED_CLOSE_HELMET;
	public static final ArmorType GILDED_DARKBLUED_GREENWICH_ARMET;
	public static final ArmorType GILDED_DARKBLUED_GREENWICH_ARMOR;
	public static final ArmorType GILDED_DARK_CLOSE_HELMET;
	public static final ArmorType GILDED_FOX_GROTESQUE_MAXIMILIAN_HELMET;
	public static final ArmorType GILDED_GRILLED_HELMET;
	public static final ArmorType GRILLED_HELMET;
	public static final ArmorType LION_HELMET;
	public static final ArmorType MAMLUK_HELMET;
	public static final ArmorType MAXIMILIAN_BURGONET;
	public static final ArmorType OPENED_SALLET;
	public static final ArmorType SPLINT;
	public static final ArmorType TILTED_PUFF_AND_SLASH_HAT;
	public static final ArmorType ALLA_TEDESCA;
	public static final ArmorType PEASCOD;
	public static final ArmorType GILDED_PEASCOD;
	public static final ArmorType DARK_PEASCOD;
	public static final ArmorType GILDED_DARK_PEASCOD;
	public static final ArmorType TWO_EYE_SLITS_SALLET;
	public static final ArmorType SALLET_WITHOUT_VISOR;
	public static final ArmorType GERMAN_BASCINET;
	public static final ArmorType LIGHT_CUMAN_HELMET;
	public static final ArmorType RED_GREATHELM;
	public static final ArmorType WHITE_GREATHELM;
	public static final ArmorType YELLOW_GREATHELM;
	public static final ArmorType GILDED_GREATHELM;
	public static final ArmorType DARK_BELLOWS_MAXIMILIAN_HELMET;

	static {
		DARK_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "dark_knight"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_KNIGHT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_ARMET = create(new ResourceLocation("magistuarmoryaddon", "dark_armet"), new ResourceLocation("magistuarmory:armet"), ARMOR_CONFIG.get("DARK_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_STECHHELM = create(new ResourceLocation("magistuarmoryaddon", "dark_stechhelm"), new ResourceLocation("magistuarmory:stechhelm"), ARMOR_CONFIG.get("DARK_STECHHELM"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_JOUSTING = create(new ResourceLocation("magistuarmoryaddon", "dark_jousting"), new ResourceLocation("magistuarmory:default"), ARMOR_CONFIG.get("DARK_JOUSTING"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_SALLET = create(new ResourceLocation("magistuarmoryaddon", "dark_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("DARK_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GOTHIC = create(new ResourceLocation("magistuarmoryaddon", "dark_gothic"), new ResourceLocation("magistuarmory:default"), ARMOR_CONFIG.get("DARK_GOTHIC"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "dark_maximilian_helmet"), new ResourceLocation("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.get("DARK_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "dark_maximilian"), new ResourceLocation("magistuarmory:default"), ARMOR_CONFIG.get("DARK_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "dark_greathelm"), new ResourceLocation("magistuarmoryaddon:greathelm"), ARMOR_CONFIG.get("DARK_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_CRUSADER = create(new ResourceLocation("magistuarmoryaddon", "dark_crusader"), new ResourceLocation("magistuarmory:default"), ARMOR_CONFIG.get("DARK_CRUSADER"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GRAND_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "dark_grand_bascinet"), new ResourceLocation("magistuarmory:grand_bascinet"), ARMOR_CONFIG.get("DARK_GRAND_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_KASTENBRUST = create(new ResourceLocation("magistuarmoryaddon", "dark_kastenbrust"), new ResourceLocation("magistuarmory:default"), ARMOR_CONFIG.get("DARK_KASTENBRUST"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SAVOYARD_HELMET = create(new ResourceLocation("magistuarmoryaddon", "savoyard_helmet"), new ResourceLocation("magistuarmoryaddon:savoyard_helmet"), ARMOR_CONFIG.get("SAVOYARD_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		MORION = create(new ResourceLocation("magistuarmoryaddon", "morion"), new ResourceLocation("magistuarmoryaddon:morion"), ARMOR_CONFIG.get("MORION"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		PIKEMAN = create(new ResourceLocation("magistuarmoryaddon", "pikeman"), new ResourceLocation("default"), ARMOR_CONFIG.get("PIKEMAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		MILANESE_ARMET = create(new ResourceLocation("magistuarmoryaddon", "milanese_armet"), new ResourceLocation("magistuarmoryaddon:milanese_armet"), ARMOR_CONFIG.get("MILANESE_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		BRITISH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "british_armet"), new ResourceLocation("magistuarmoryaddon:british_armet"), ARMOR_CONFIG.get("BRITISH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		AVANT = create(new ResourceLocation("magistuarmoryaddon", "avant"), new ResourceLocation("default"), ARMOR_CONFIG.get("AVANT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		VISORED_KETTLEHAT = create(new ResourceLocation("magistuarmoryaddon", "visored_kettlehat"), new ResourceLocation("magistuarmoryaddon:visored_kettlehat"), ARMOR_CONFIG.get("VISORED_KETTLEHAT"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CERVELLIERE = create(new ResourceLocation("magistuarmoryaddon", "cervelliere"), new ResourceLocation("default"), ARMOR_CONFIG.get("CERVELLIERE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CLOSED_BARBUTE = create(new ResourceLocation("magistuarmoryaddon", "closed_barbute"), new ResourceLocation("default"), ARMOR_CONFIG.get("CLOSED_BARBUTE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		BICOQUE = create(new ResourceLocation("magistuarmoryaddon", "bicoque"), new ResourceLocation("magistuarmoryaddon:bicoque"), ARMOR_CONFIG.get("BICOQUE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LINEN = create(new ResourceLocation("magistuarmoryaddon", "linen"), new ResourceLocation("magistuarmoryaddon:underarmor"), ARMOR_CONFIG.get("LINEN"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		SALLET_WITHOUT_NECK_PROTECTION = create(new ResourceLocation("magistuarmoryaddon", "sallet_without_neck_protection"), new ResourceLocation("magistuarmoryaddon:sallet_without_neck_protection"), ARMOR_CONFIG.get("SALLET_WITHOUT_NECK_PROTECTION"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		BELLOWS_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "bellows_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:bellows_maximilian_helmet"), ARMOR_CONFIG.get("BELLOWS_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		KULAH_KHUD = create(new ResourceLocation("magistuarmoryaddon", "kulah_khud"), new ResourceLocation("magistuarmoryaddon:kulah_khud"), ARMOR_CONFIG.get("KULAH_KHUD"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CUMAN_CAPTAIN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "mirror"), new ResourceLocation("magistuarmoryaddon:kulah_khud"), ARMOR_CONFIG.get("CUMAN_CAPTAIN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		MIRROR = create(new ResourceLocation("magistuarmoryaddon", "mirror"), new ResourceLocation("default"), ARMOR_CONFIG.get("MIRROR"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SARACEN = create(new ResourceLocation("magistuarmoryaddon", "saracen"), new ResourceLocation("default"), ARMOR_CONFIG.get("SARACEN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		EARLY_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "early_greathelm"), new ResourceLocation("magistuarmoryaddon:early_greathelm"), ARMOR_CONFIG.get("EARLY_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		XIII_CENTURY_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "xiii_century_knight"), new ResourceLocation("default"), ARMOR_CONFIG.get("XIII_CENTURY_KNIGHT"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		KLAPPVISOR_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "klappvisor_bascinet"), new ResourceLocation("magistuarmoryaddon:klappvisor_bascinet"), ARMOR_CONFIG.get("KLAPPVISOR_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LATE_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "late_bascinet"), new ResourceLocation("magistuarmoryaddon:late_bascinet"), ARMOR_CONFIG.get("LATE_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LOBSTER_TAILED_HELMET = create(new ResourceLocation("magistuarmoryaddon", "lobster_tailed_helmet"), new ResourceLocation("magistuarmoryaddon:lobster_tailed_helmet"), ARMOR_CONFIG.get("LOBSTER_TAILED_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CHAPEL = create(new ResourceLocation("magistuarmoryaddon", "chapel"), new ResourceLocation("magistuarmoryaddon:chapel"), ARMOR_CONFIG.get("CHAPEL"), SoundEvents.ARMOR_EQUIP_LEATHER, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CHAINED_GAMBESON = create(new ResourceLocation("magistuarmoryaddon", "chained_gambeson"), new ResourceLocation("default"), ARMOR_CONFIG.get("CHAINED_GAMBESON"), SoundEvents.ARMOR_EQUIP_LEATHER, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		TABLET_HELMET = create(new ResourceLocation("magistuarmoryaddon", "tablet_helmet"), new ResourceLocation("default"), ARMOR_CONFIG.get("TABLET_HELMET"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LATE_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "late_greathelm"), new ResourceLocation("magistuarmoryaddon:late_greathelm"), ARMOR_CONFIG.get("LATE_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		BURGUNDIAN_KETTLEHAT = create(new ResourceLocation("magistuarmoryaddon", "burgundian_kettlehat"), new ResourceLocation("magistuarmoryaddon:burgundian_kettlehat"), ARMOR_CONFIG.get("BURGUNDIAN_KETTLEHAT"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CLOSED_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "closed_burgonet"), new ResourceLocation("magistuarmoryaddon:closed_burgonet"), ARMOR_CONFIG.get("CLOSED_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		HEAVY_CUIRASSIER = create(new ResourceLocation("magistuarmoryaddon", "heavy_cuirassier"), new ResourceLocation("default"), ARMOR_CONFIG.get("HEAVY_CUIRASSIER"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_HEAVY_CUIRASSIER = create(new ResourceLocation("magistuarmoryaddon", "dark_heavy_cuirassier"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_HEAVY_CUIRASSIER"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LIGHT_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "light_burgonet"), new ResourceLocation("magistuarmoryaddon:late_burgonet"), ARMOR_CONFIG.get("LIGHT_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LATE_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "late_burgonet"), new ResourceLocation("magistuarmoryaddon:late_burgonet"), ARMOR_CONFIG.get("LATE_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DEVILISH_GROTESQUE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "devilish_grotesque_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:devilish_grotesque_maximilian_helmet"), ARMOR_CONFIG.get("DEVILISH_GROTESQUE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FACIAL_GROTESQUE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "facial_grotesque_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:facial_grotesque_maximilian_helmet"), ARMOR_CONFIG.get("FACIAL_GROTESQUE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GILDED_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "dark_gilded_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("DARK_GILDED_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GILDED_GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "dark_gilded_greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_GILDED_GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "dark_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("DARK_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "dark_greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LATE_SALLET = create(new ResourceLocation("magistuarmoryaddon", "late_sallet"), new ResourceLocation("magistuarmoryaddon:late_sallet"), ARMOR_CONFIG.get("LATE_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_LATE_SALLET = create(new ResourceLocation("magistuarmoryaddon", "dark_late_sallet"), new ResourceLocation("magistuarmoryaddon:late_sallet"), ARMOR_CONFIG.get("DARK_LATE_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		STEEL_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "steel_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:steel_puff_and_slash"), ARMOR_CONFIG.get("STEEL_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_STEEL_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "gilded_steel_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:steel_puff_and_slash"), ARMOR_CONFIG.get("GILDED_STEEL_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		STURMHAUBE = create(new ResourceLocation("magistuarmoryaddon", "sturmhaube"), new ResourceLocation("magistuarmoryaddon:sturmhaube"), ARMOR_CONFIG.get("STURMHAUBE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "silvered_dark_bellows_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:bellows_maximilian_helmet"), ARMOR_CONFIG.get("SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SILVERED_DARK_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "silvered_dark_maximilian_helmet"), new ResourceLocation("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.get("SILVERED_DARK_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SILVERED_DARK_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "silvered_dark_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("SILVERED_DARK_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GRAND_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "gilded_grand_bascinet"), new ResourceLocation("magistuarmory:grand_bascinet"), ARMOR_CONFIG.get("GILDED_GRAND_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CEREMONIAL_KASTENBRUST = create(new ResourceLocation("magistuarmoryaddon", "ceremonial_kastenbrust"), new ResourceLocation("default"), ARMOR_CONFIG.get("CEREMONIAL_KASTENBRUST"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_XIV_CENTURY_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "gilded_xivcenturyknight"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_XIV_CENTURY_KNIGHT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GALLOWGLASS = create(new ResourceLocation("magistuarmoryaddon", "gallowglass"), new ResourceLocation("default"), ARMOR_CONFIG.get("GALLOWGLASS"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		ENGLISH_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "english_knight"), new ResourceLocation("default"), ARMOR_CONFIG.get("ENGLISH_KNIGHT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_HALF_ARMOR = create(new ResourceLocation("magistuarmoryaddon", "gilded_half_armor"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_HALF_ARMOR"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_EXQUISITE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_exquisite_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:exquisite_armet"), ARMOR_CONFIG.get("GILDED_EXQUISITE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_maximilian_helmet"), new ResourceLocation("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.get("GILDED_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "gilded_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		COAT_OF_PLATES = create(new ResourceLocation("magistuarmoryaddon", "coat_of_plates"), new ResourceLocation("default"), ARMOR_CONFIG.get("COAT_OF_PLATES"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SILVERED_DARK_HALF_ARMOR = create(new ResourceLocation("magistuarmoryaddon", "silvered_dark_half_armor"), new ResourceLocation("default"), ARMOR_CONFIG.get("SILVERED_DARK_HALF_ARMOR"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARK_SALLET = create(new ResourceLocation("magistuarmoryaddon", "gilded_dark_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("GILDED_DARK_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARK_GOTHIC = create(new ResourceLocation("magistuarmoryaddon", "gilded_dark_gothic"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_DARK_GOTHIC"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_SALLET = create(new ResourceLocation("magistuarmoryaddon", "gilded_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("GILDED_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GOTHIC = create(new ResourceLocation("magistuarmoryaddon", "gilded_gothic"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_GOTHIC"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("GILDED_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "gilded_greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LANDSKNECHT_ORANGE_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_orange_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_ORANGE_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_MAGENTA_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_magenta_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_MAGENTA_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_LIGHT_BLUE_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_light_blue_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_LIGHT_BLUE_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_YELLOW_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_yellow_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_YELLOW_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_LIME_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_lime_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_LIME_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_PINK_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_pink_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_PINK_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_GRAY_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_gray_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_GRAY_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_LIGHT_GRAY_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_light_gray_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_LIGHT_GRAY_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_CYAN_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_cyan_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_CYAN_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_PURPLE_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_purple_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_PURPLE_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_BLUE_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_blue_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_BLUE_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_BROWN_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_brown_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_BROWN_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_GREEN_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_green_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_GREEN_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_RED_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_red_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_RED_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_BLACK_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_black_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_BLACK_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LANDSKNECHT_WHITE_HAT = create(new ResourceLocation("magistuarmoryaddon", "landsknecht_white_hat"), new ResourceLocation("magistuarmoryaddon:landsknecht_hat"), ARMOR_CONFIG.get("LANDSKNECHT_WHITE_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		ORANGE_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "orange_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("ORANGE_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		MAGENTA_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "magenta_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("MAGENTA_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LIGHT_BLUE_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "light_blue_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("LIGHT_BLUE_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		YELLOW_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "yellow_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("YELLOW_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LIME_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "lime_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("LIME_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		PINK_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "pink_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("PINK_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		GRAY_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "gray_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("GRAY_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		LIGHT_GRAY_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "light_gray_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("LIGHT_GRAY_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		CYAN_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "cyan_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("CYAN_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		PURPLE_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "purple_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("PURPLE_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		BLUE_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "blue_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("BLUE_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		BROWN_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "brown_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("BROWN_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		GREEN_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "green_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("GREEN_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		RED_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "red_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("RED_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		BLACK_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "black_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("BLACK_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		WHITE_PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "white_puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("WHITE_PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		PUFF_AND_SLASH = create(new ResourceLocation("magistuarmoryaddon", "puff_and_slash"), new ResourceLocation("magistuarmoryaddon:puff_and_slash"), ARMOR_CONFIG.get("PUFF_AND_SLASH"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(Items.LEATHER));
		SCALE_HELMET = create(new ResourceLocation("magistuarmoryaddon", "scale_helmet"), new ResourceLocation("default"), ARMOR_CONFIG.get("SCALE_HELMET"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CONDOTTIERO_CAP = create(new ResourceLocation("magistuarmoryaddon", "condottiero_cap"), new ResourceLocation("magistuarmoryaddon:condottiero_cap"), ARMOR_CONFIG.get("CONDOTTIERO_CAP"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		SUGARLOAF_HELMET = create(new ResourceLocation("magistuarmoryaddon", "sugarloaf_helmet"), new ResourceLocation("magistuarmoryaddon:sugarloaf_helmet"), ARMOR_CONFIG.get("SUGARLOAF_HELMET"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_SUGARLOAF_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_sugarloaf_helmet"), new ResourceLocation("magistuarmoryaddon:sugarloaf_helmet"), ARMOR_CONFIG.get("GILDED_SUGARLOAF_HELMET"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		PATRICIAN_TUHER_HELMET = create(new ResourceLocation("magistuarmoryaddon", "patrician_tuher_helmet"), new ResourceLocation("magistuarmoryaddon:patrician_tuher_helmet"), ARMOR_CONFIG.get("PATRICIAN_TUHER_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LATE_KETTLEHAT = create(new ResourceLocation("magistuarmoryaddon", "late_kettlehat"), new ResourceLocation("magistuarmoryaddon:late_kettlehat"), ARMOR_CONFIG.get("LATE_KETTLEHAT"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CLOSE_HELMET = create(new ResourceLocation("magistuarmoryaddon", "close_helmet"), new ResourceLocation("magistuarmoryaddon:close_helmet"), ARMOR_CONFIG.get("CLOSE_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		EXQUISITE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "exquisite_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:exquisite_maximilian_helmet"), ARMOR_CONFIG.get("EXQUISITE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		PROTO_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "proto_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("PROTO_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_PROTO_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "dark_proto_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_PROTO_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		HEAVY_BRIGANDINE = create(new ResourceLocation("magistuarmoryaddon", "heavy_brigandine"), new ResourceLocation("default"), ARMOR_CONFIG.get("HEAVY_BRIGANDINE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_HEAVY_BRIGANDINE = create(new ResourceLocation("magistuarmoryaddon", "gilded_heavy_brigandine"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_HEAVY_BRIGANDINE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_HEAVY_BRIGANDINE = create(new ResourceLocation("magistuarmoryaddon", "dark_heavy_brigandine"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_HEAVY_BRIGANDINE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CABASSET = create(new ResourceLocation("magistuarmoryaddon", "cabasset"), new ResourceLocation("magistuarmoryaddon:cabasset"), ARMOR_CONFIG.get("CABASSET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_CABASSET = create(new ResourceLocation("magistuarmoryaddon", "gilded_cabasset"), new ResourceLocation("magistuarmoryaddon:cabasset"), ARMOR_CONFIG.get("GILDED_CABASSET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		EARLY_CABASSET = create(new ResourceLocation("magistuarmoryaddon", "early_cabasset"), new ResourceLocation("magistuarmoryaddon:early_cabasset"), ARMOR_CONFIG.get("EARLY_CABASSET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_EARLY_CABASSET = create(new ResourceLocation("magistuarmoryaddon", "dark_early_cabasset"), new ResourceLocation("magistuarmoryaddon:early_cabasset"), ARMOR_CONFIG.get("DARK_EARLY_CABASSET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_EARLY_CABASSET = create(new ResourceLocation("magistuarmoryaddon", "gilded_early_cabasset"), new ResourceLocation("magistuarmoryaddon:early_cabasset"), ARMOR_CONFIG.get("GILDED_EARLY_CABASSET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		STRAW_HAT = create(new ResourceLocation("magistuarmoryaddon", "straw_hat"), new ResourceLocation("magistuarmoryaddon:straw_hat"), ARMOR_CONFIG.get("STRAW_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		FANCY_HAT = create(new ResourceLocation("magistuarmoryaddon", "fancy_hat"), new ResourceLocation("magistuarmoryaddon:fancy_hat"), ARMOR_CONFIG.get("FANCY_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		TUNIC = create(new ResourceLocation("magistuarmoryaddon", "tunic"), new ResourceLocation("magistuarmoryaddon:tunic"), ARMOR_CONFIG.get("TUNIC"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		EMBOSED_PARADE_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "embosed_parade_burgonet"), new ResourceLocation("magistuarmoryaddon:parade_burgonet"), ARMOR_CONFIG.get("EMBOSED_PARADE_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		EMBOSED_PARADE = create(new ResourceLocation("magistuarmoryaddon", "embosed_parade"), new ResourceLocation("default"), ARMOR_CONFIG.get("EMBOSED_PARADE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GILDED_PARADE_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "dark_gilded_parade_burgonet"), new ResourceLocation("magistuarmoryaddon:parade_burgonet"), ARMOR_CONFIG.get("DARK_GILDED_PARADE_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_GILDED_PARADE = create(new ResourceLocation("magistuarmoryaddon", "dark_gilded_parade"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_GILDED_PARADE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DOUBLET = create(new ResourceLocation("magistuarmoryaddon", "doublet"), new ResourceLocation("default"), ARMOR_CONFIG.get("DOUBLET"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		GOLDEN_NECKLACE = create(new ResourceLocation("magistuarmoryaddon", "golden_necklace"), new ResourceLocation("magistuarmoryaddon:necklace"), ARMOR_CONFIG.get("GOLDEN_NECKLACE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/gold" : "c:gold_ingots");
		SILVER_NECKLACE = create(new ResourceLocation("magistuarmoryaddon", "silver_necklace"), new ResourceLocation("magistuarmoryaddon:necklace"), ARMOR_CONFIG.get("SILVER_NECKLACE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/gold" : "c:gold_ingots");
		SILVER_CROSS_NECKLACE = create(new ResourceLocation("magistuarmoryaddon", "silver_cross_necklace"), new ResourceLocation("magistuarmoryaddon:necklace"), ARMOR_CONFIG.get("SILVER_CROSS_NECKLACE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/silver" : "c:silver_ingots");
		GOLDEN_CROSS_NECKLACE = create(new ResourceLocation("magistuarmoryaddon", "golden_cross_necklace"), new ResourceLocation("magistuarmoryaddon:necklace"), ARMOR_CONFIG.get("GOLDEN_CROSS_NECKLACE"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/silver" : "c:silver_ingots");
		ARTICULATED = create(new ResourceLocation("magistuarmoryaddon", "articulated"), new ResourceLocation("default"), ARMOR_CONFIG.get("ARTICULATED"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		CUMAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "cuman_helmet"), new ResourceLocation("magistuarmoryaddon:cuman_helmet"), ARMOR_CONFIG.get("CUMAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_GOTHIC = create(new ResourceLocation("magistuarmoryaddon", "darkblued_gothic"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARKBLUED_GOTHIC"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "darkblued_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("DARKBLUED_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "darkblued_greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARKBLUED_GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_KASTENBRUST = create(new ResourceLocation("magistuarmoryaddon", "darkblued_kastenbrust"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARKBLUED_KASTENBRUST"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_ARMET = create(new ResourceLocation("magistuarmoryaddon", "darkblued_armet"), new ResourceLocation("magistuarmory:armet"), ARMOR_CONFIG.get("DARKBLUED_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "darkblued_knight"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARKBLUED_KNIGHT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "darkblued_maximilian_helmet"), new ResourceLocation("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.get("DARKBLUED_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "darkblued_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARKBLUED_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARKBLUED_SALLET = create(new ResourceLocation("magistuarmoryaddon", "darkblued_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("DARKBLUED_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		ENGRAVED_CLOSE_HELMET = create(new ResourceLocation("magistuarmoryaddon", "engraved_close_helmet"), new ResourceLocation("magistuarmoryaddon:close_helmet"), ARMOR_CONFIG.get("ENGRAVED_CLOSE_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		ENGRAVED = create(new ResourceLocation("magistuarmoryaddon", "engraved"), new ResourceLocation("default"), ARMOR_CONFIG.get("ENGRAVED"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FOX_GROTESQUE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "fox_grotesque_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:fox_grotesque_maximilian_helmet"), ARMOR_CONFIG.get("FOX_GROTESQUE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_ARMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_armet"), new ResourceLocation("magistuarmory:armet"), ARMOR_CONFIG.get("FULLY_GILDED_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_ARTICULATED = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_articulated"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_ARTICULATED"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_GOTHIC = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_gothic"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_GOTHIC"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_GRAND_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_grand_bascinet"), new ResourceLocation("magistuarmory:grand_bascinet"), ARMOR_CONFIG.get("FULLY_GILDED_GRAND_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("FULLY_GILDED_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_GREENWICH = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_greenwich"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_GREENWICH"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_GRILLED_HELMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_grilled_helmet"), new ResourceLocation("magistuarmoryaddon:grilled_helmet"), ARMOR_CONFIG.get("FULLY_GILDED_GRILLED_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_JOUSTING_HELMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_jousting_helmet"), new ResourceLocation("magistuarmory:stechhelm"), ARMOR_CONFIG.get("FULLY_GILDED_JOUSTING_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_JOUSTING = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_jousting"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_JOUSTING"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_KASTENBRUST = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_kastenbrust"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_KASTENBRUST"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_KNIGHT = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_knight"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_KNIGHT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_maximilian_helmet"), new ResourceLocation("magistuarmory:maximilian_helmet"), ARMOR_CONFIG.get("FULLY_GILDED_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_MAXIMILIAN = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_maximilian"), new ResourceLocation("default"), ARMOR_CONFIG.get("FULLY_GILDED_MAXIMILIAN"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_MILANESE_ARMET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_milanese_armet"), new ResourceLocation("magistuarmoryaddon:milanese_armet"), ARMOR_CONFIG.get("FULLY_GILDED_MILANESE_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		FULLY_GILDED_SALLET = create(new ResourceLocation("magistuarmoryaddon", "fully_gilded_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("FULLY_GILDED_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_CHAINMAIL = create(new ResourceLocation("magistuarmoryaddon", "gilded_chainmail"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_CHAINMAIL"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_CLOSE_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_close_helmet"), new ResourceLocation("magistuarmoryaddon:close_helmet"), ARMOR_CONFIG.get("GILDED_CLOSE_HELMET"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARKBLUED_GREENWICH_ARMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_darkblued_greenwich_armet"), new ResourceLocation("magistuarmoryaddon:greenwich_armet"), ARMOR_CONFIG.get("GILDED_DARKBLUED_GREENWICH_ARMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARKBLUED_GREENWICH_ARMOR = create(new ResourceLocation("magistuarmoryaddon", "gilded_darkblued_greenwich_armor"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_DARKBLUED_GREENWICH_ARMOR"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARK_CLOSE_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_dark_close_helmet"), new ResourceLocation("magistuarmoryaddon:close_helmet"), ARMOR_CONFIG.get("GILDED_DARK_CLOSE_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_FOX_GROTESQUE_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_fox_grotesque_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:fox_grotesque_maximilian_helmet"), ARMOR_CONFIG.get("GILDED_FOX_GROTESQUE_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GRILLED_HELMET = create(new ResourceLocation("magistuarmoryaddon", "gilded_grilled_helmet"), new ResourceLocation("magistuarmoryaddon:grilled_helmet"), ARMOR_CONFIG.get("GILDED_GRILLED_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GRILLED_HELMET = create(new ResourceLocation("magistuarmoryaddon", "grilled_helmet"), new ResourceLocation("magistuarmoryaddon:grilled_helmet"), ARMOR_CONFIG.get("GRILLED_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LION_HELMET = create(new ResourceLocation("magistuarmoryaddon", "lion_helmet"), new ResourceLocation("magistuarmoryaddon:lion_helmet"), ARMOR_CONFIG.get("LION_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
		MAMLUK_HELMET = create(new ResourceLocation("magistuarmoryaddon", "mamluk_helmet"), new ResourceLocation("magistuarmoryaddon:kulah_khud"), ARMOR_CONFIG.get("MAMLUK_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		MAXIMILIAN_BURGONET = create(new ResourceLocation("magistuarmoryaddon", "maximilian_burgonet"), new ResourceLocation("magistuarmoryaddon:maximilian_burgonet"), ARMOR_CONFIG.get("MAXIMILIAN_BURGONET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		OPENED_SALLET = create(new ResourceLocation("magistuarmoryaddon", "opened_sallet"), new ResourceLocation("magistuarmoryaddon:opened_sallet"), ARMOR_CONFIG.get("OPENED_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SPLINT = create(new ResourceLocation("magistuarmoryaddon", "splint"), new ResourceLocation("default"), ARMOR_CONFIG.get("SPLINT"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		TILTED_PUFF_AND_SLASH_HAT = create(new ResourceLocation("magistuarmoryaddon", "tilted_puff_and_slash_hat"), new ResourceLocation("magistuarmoryaddon:tilted_puff_and_slash_hat"), ARMOR_CONFIG.get("TILTED_PUFF_AND_SLASH_HAT"), SoundEvents.ARMOR_EQUIP_LEATHER, () -> Ingredient.of(TagKey.create(Registries.ITEM, new ResourceLocation("magistuarmory:woolen_fabric"))));
		ALLA_TEDESCA = create(new ResourceLocation("magistuarmoryaddon", "alla_tedesca"), new ResourceLocation("default"), ARMOR_CONFIG.get("ALLA_TEDESCA"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		PEASCOD = create(new ResourceLocation("magistuarmoryaddon", "peascod"), new ResourceLocation("default"), ARMOR_CONFIG.get("PEASCOD"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_PEASCOD = create(new ResourceLocation("magistuarmoryaddon", "gilded_peascod"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_PEASCOD"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_PEASCOD = create(new ResourceLocation("magistuarmoryaddon", "dark_peascod"), new ResourceLocation("default"), ARMOR_CONFIG.get("DARK_PEASCOD"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_DARK_PEASCOD = create(new ResourceLocation("magistuarmoryaddon", "gilded_dark_peascod"), new ResourceLocation("default"), ARMOR_CONFIG.get("GILDED_DARK_PEASCOD"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		TWO_EYE_SLITS_SALLET = create(new ResourceLocation("magistuarmoryaddon", "two_eye_slits_sallet"), new ResourceLocation("magistuarmoryaddon:sallet"), ARMOR_CONFIG.get("TWO_EYE_SLITS_SALLET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		SALLET_WITHOUT_VISOR = create(new ResourceLocation("magistuarmoryaddon", "sallet_without_visor"), new ResourceLocation("magistuarmoryaddon:sallet_without_visor"), ARMOR_CONFIG.get("SALLET_WITHOUT_VISOR"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GERMAN_BASCINET = create(new ResourceLocation("magistuarmoryaddon", "german_bascinet"), new ResourceLocation("magistuarmoryaddon:german_bascinet"), ARMOR_CONFIG.get("GERMAN_BASCINET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		LIGHT_CUMAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "light_cuman_helmet"), new ResourceLocation("magistuarmoryaddon:cuman_helmet"), ARMOR_CONFIG.get("LIGHT_CUMAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		RED_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "red_greathelm"), new ResourceLocation("magistuarmoryaddon:greathelm"), ARMOR_CONFIG.get("RED_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		WHITE_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "white_greathelm"), new ResourceLocation("magistuarmoryaddon:greathelm"), ARMOR_CONFIG.get("WHITE_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		YELLOW_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "yellow_greathelm"), new ResourceLocation("magistuarmoryaddon:greathelm"), ARMOR_CONFIG.get("YELLOW_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		GILDED_GREATHELM = create(new ResourceLocation("magistuarmoryaddon", "gilded_greathelm"), new ResourceLocation("magistuarmoryaddon:greathelm"), ARMOR_CONFIG.get("GILDED_GREATHELM"), SoundEvents.ARMOR_EQUIP_CHAIN, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
		DARK_BELLOWS_MAXIMILIAN_HELMET = create(new ResourceLocation("magistuarmoryaddon", "dark_bellows_maximilian_helmet"), new ResourceLocation("magistuarmoryaddon:bellows_maximilian_helmet"), ARMOR_CONFIG.get("DARK_BELLOWS_MAXIMILIAN_HELMET"), SoundEvents.ARMOR_EQUIP_IRON, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	}



	private static ArmorType create(ResourceLocation location,
									ResourceLocation modelLocation,
									com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config,
									SoundEvent equipSound,
									String repairItemTag) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[] {config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[] {config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled, repairItemTag);
	}

	private static ArmorType create(ResourceLocation location,
									ResourceLocation modelLocation,
									com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config,
									SoundEvent equipSound,
									Supplier<Ingredient> ingredientSupplier) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[] {config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[] {config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled, ingredientSupplier);
	}

	private static ArmorType create(ResourceLocation location,
									ResourceLocation modelLocation,
									com.magistuarmory.config.ArmorConfig.ArmorTypeConfig config,
									SoundEvent equipSound) {
		return new ArmorType(location, modelLocation, config.toughness, config.knockbackResistance, new Integer[] {config.bootsDurability, config.leggingsDurability, config.chestplateDurability, config.helmetDurability}, new Integer[] {config.bootsDefense, config.leggingsDefense, config.chestplateDefense, config.helmetDefense}, config.enchantmentValue, equipSound, config.enabled);
	}
}
