package com.magistuarmory.addon.item.armor;

import com.magistuarmory.EpicKnights;
import com.magistuarmory.addon.EpicKnightsAddon;
import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;

public class AddonArmorTypes
{
	public static final ArmorType DARK_KNIGHT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_knight"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_armet"), new ResourceLocation(EpicKnights.ID, "armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_STECHHELM = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_stechhelm"), new ResourceLocation(EpicKnights.ID, "stechhelm"), 2.0f, 1.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_JOUSTING = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_jousting"), new ResourceLocation(EpicKnights.ID, "default"), 2.0f, 1.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_SALLET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_sallet"), new ResourceLocation(EpicKnightsAddon.ID, "sallet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_GOTHIC = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_gothic"), new ResourceLocation(EpicKnights.ID, "default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_maximilian_helmet"), new ResourceLocation(EpicKnights.ID, "maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_MAXIMILIAN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_maximilian"), new ResourceLocation(EpicKnights.ID, "default"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_CRUSADER = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_crusader"), new ResourceLocation(EpicKnights.ID, "default"), 0.6f, 0.0f, new Integer[] { 150, 280, 295, 220 }, new Integer[] { 1, 5, 6, 3 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_KASTENBRUST = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_kastenbrust"), new ResourceLocation(EpicKnights.ID, "default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_GRAND_BASCINET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_grand_bascinet"), new ResourceLocation(EpicKnights.ID, "grand_bascinet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SAVOYARD_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "savoyard_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "savoyard_helmet"), 1.25f, 0.0f, new Integer[] { 150, 0, 315, 225 }, new Integer[] { 2, 0, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType MORION = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "morion"), new ResourceLocation(EpicKnightsAddon.ID, "morion"), 0.6f, 0.0f, new Integer[] { 150, 0, 315, 180 }, new Integer[] { 2, 0, 8, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType PIKEMAN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "pikeman"), new ResourceLocation("default"), 0.6f, 0.0f, new Integer[] { 170, 0, 365, 180 }, new Integer[] { 2, 0, 8, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType MILANESE_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "milanese_armet"), new ResourceLocation(EpicKnightsAddon.ID, "milanese_armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType BRITISH_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "british_armet"), new ResourceLocation(EpicKnightsAddon.ID, "british_armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType AVANT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "avant"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType VISORED_KETTLEHAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "visored_kettlehat"), new ResourceLocation(EpicKnightsAddon.ID, "visored_kettlehat"), 0.6f, 0.0f, new Integer[] { 220, 290, 210, 260 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType CERVELLIERE = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "cervelliere"), new ResourceLocation("default"), 0.25f, 0.0f, new Integer[] { 180, 290, 315, 170 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType CLOSED_BARBUTE = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "closed_barbute"), new ResourceLocation("default"), 1.0f, 0.5f, new Integer[] { 220, 290, 210, 260 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BICOQUE = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "bicoque"), new ResourceLocation(EpicKnightsAddon.ID, "bicoque"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LINEN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "linen"), new ResourceLocation(EpicKnightsAddon.ID, "underarmor"), 0.0f, 0.0f, new Integer[] { 150, 200, 250, 200 }, new Integer[] { 0, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));

	public static final ArmorType SALLET_WITHOUT_NECK_PROTECTION = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "sallet_without_neck_protection"), new ResourceLocation(EpicKnightsAddon.ID, "sallet_without_neck_protection"), 0.7f, 0.0f, new Integer[] { 230, 315, 335, 245 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BELLOWS_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "bellows_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "bellows_maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType KULAH_KHUD = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "kulah_khud"), new ResourceLocation(EpicKnightsAddon.ID, "kulah_khud"), 0.6f, 0.0f, new Integer[] { 150, 315, 200, 170 }, new Integer[] { 2, 0, 8, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType CUMAN_CAPTAIN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "mirror"), new ResourceLocation(EpicKnightsAddon.ID, "kulah_khud"), 0.8f, 0.0f, new Integer[] { 150, 325, 200, 200 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType MIRROR = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "mirror"), new ResourceLocation("default"), 0.8f, 0.0f, new Integer[] { 150, 200, 325, 200 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SARACEN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "saracen"), new ResourceLocation("default"), 0.2f, 0.0f, new Integer[] { 200, 200, 270, 190 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType EARLY_GREATHELM = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "early_greathelm"), new ResourceLocation(EpicKnightsAddon.ID, "early_greathelm"), 0.4f, 0.0f, new Integer[] { 150, 280, 295, 220 }, new Integer[] { 1, 5, 6, 3 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType XIII_CENTURY_KNIGHT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "xiii_century_knight"), new ResourceLocation("default"), 0.35f, 0.0f, new Integer[] { 200, 160, 270, 220 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType KLAPPVISOR_BASCINET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "klappvisor_bascinet"), new ResourceLocation(EpicKnightsAddon.ID, "klappvisor_bascinet"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType LATE_BASCINET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "late_bascinet"), new ResourceLocation(EpicKnightsAddon.ID, "late_bascinet"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LOBSTER_TAILED_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "lobster_tailed_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "lobster_tailed_helmet"), 0.6f, 0.0f, new Integer[] { 150, 0, 315, 180 }, new Integer[] { 1, 0, 6, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");




	public static final ArmorType CHAPEL = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "chapel"), new ResourceLocation(EpicKnightsAddon.ID, "chapel"), 0.3f, 0.0f, new Integer[] { 0, 0, 0, 220 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType CHAINED_GAMBESON = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "chained_gambeson"), new ResourceLocation("default"), 0.2f, 0.0f, new Integer[] { 150, 0, 192, 132 }, new Integer[] { 2, 0, 3, 2 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType TABLET_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "tablet_helmet"), new ResourceLocation("default"), 0.2f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LATE_GREATHELM = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "late_greathelm"), new ResourceLocation(EpicKnightsAddon.ID, "late_greathelm"), 1.25f, 1.0f, new Integer[] { 0, 0, 0, 300 }, new Integer[] { 0, 0, 0, 3 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType BURGUNDIAN_KETTLEHAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "burgundian_kettlehat"), new ResourceLocation(EpicKnightsAddon.ID, "burgundian_kettlehat"), 0.3f, 0.0f, new Integer[] { 0, 0, 0, 230 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType CLOSED_BURGONET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "closed_burgonet"), new ResourceLocation(EpicKnightsAddon.ID, "closed_burgonet"), 1.25f, 0.5f, new Integer[] { 0, 0, 0, 275 }, new Integer[] { 0, 0, 0, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType HEAVY_CUIRASSIER = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "heavy_cuirassier"), new ResourceLocation("default"), 1.4f, 0.8f, new Integer[] { 253, 346, 368, 302 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_HEAVY_CUIRASSIER = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_heavy_cuirassier"), new ResourceLocation("default"), 1.4f, 0.8f, new Integer[] { 253, 346, 368, 302 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LIGHT_BURGONET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "light_burgonet"), new ResourceLocation(EpicKnightsAddon.ID, "late_burgonet"), 0.5f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LATE_BURGONET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "late_burgonet"), new ResourceLocation(EpicKnightsAddon.ID, "late_burgonet"), 0.6f, 0.0f, new Integer[] { 0, 0, 0, 250 }, new Integer[] { 0, 0, 0, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DEVILISH_GROTESQUE_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "devilish_grotesque_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "devilish_grotesque_maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 0, 0, 0, 385 }, new Integer[] { 0, 0, 0, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType FACIAL_GROTESQUE_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "facial_grotesque_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "facial_grotesque_maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 0, 0, 0, 385 }, new Integer[] { 0, 0, 0, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType DARK_GILDED_GREENWICH_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_gilded_greenwich_armet"), new ResourceLocation(EpicKnightsAddon.ID, "greenwich_armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType DARK_GILDED_GREENWICH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "dark_gilded_greenwich"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType LATE_SALLET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "late_sallet"), new ResourceLocation(EpicKnightsAddon.ID, "late_sallet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType STEEL_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "steel_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "steel_puff_and_slash"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_STEEL_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_steel_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "steel_puff_and_slash"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType STURMHAUBE = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "sturmhaube"),  new ResourceLocation(EpicKnightsAddon.ID, "sturmhaube"), 0.6f, 0.0f, new Integer[] { 0, 0, 0, 210 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "silvered_dark_bellows_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "bellows_maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType SILVERED_DARK_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "silvered_dark_maximilian_helmet"), new ResourceLocation(EpicKnights.ID, "maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType SILVERED_DARK_MAXIMILIAN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "silvered_dark_maximilian"), new ResourceLocation("default"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

//	public static final ArmorType GILDED_DARK_BELLOWS_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_bellows_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "bellows_maximilian_helmet"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
//	public static final ArmorType GILDED_DARK_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_maximilian_helmet"), new ResourceLocation(EpicKnights.ID, "maximilian_helmet"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
//	public static final ArmorType GILDED_DARK_MAXIMILIAN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_maximilian"), new ResourceLocation("default"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_GRAND_BASCINET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_grand_bascinet"), new ResourceLocation(EpicKnights.ID, "grand_bascinet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType CEREMONIAL_KASTENBRUST = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "ceremonial_kastenbrust"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_XIV_CENTURY_KNIGHT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_xivcenturyknight"), new ResourceLocation("default"), 1.25f, 0.0f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GALLOWGLASS = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gallowglass"), new ResourceLocation("default"), 0.0f, 0.0f, new Integer[] { 170, 235, 250, 205 }, new Integer[] { 1, 4, 5, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType ENGLISH_KNIGHT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "english_knight"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_HALF_ARMOR = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_half_armor"), new ResourceLocation("default"), 0.5f, 0.0f, new Integer[] { 180, 290, 315, 170 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_EXQUISITE_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_exquisite_maximilian_helmet"), new ResourceLocation(EpicKnightsAddon.ID, "exquisite_armet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_maximilian_helmet"), new ResourceLocation(EpicKnights.ID, "maximilian_helmet"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType GILDED_MAXIMILIAN = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_maximilian"), new ResourceLocation("default"), 1.8f, 0.5f, new Integer[] { 345, 500, 440, 385 }, new Integer[] { 3, 6, 9, 4 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType COAT_OF_PLATES = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "coat_of_plates"), new ResourceLocation("default"), 0.0f, 0.0f, new Integer[] { 200, 270, 200, 240 }, new Integer[] { 2, 4, 5, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType SILVERED_DARK_HALF_ARMOR = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "silvered_dark_half_armor"), new ResourceLocation("default"), 0.5f, 0.0f, new Integer[] { 180, 290, 315, 170 }, new Integer[] { 2, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_DARK_SALLET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_sallet"), new ResourceLocation(EpicKnightsAddon.ID, "sallet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType GILDED_DARK_GOTHIC = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_gothic"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_SALLET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_sallet"), new ResourceLocation(EpicKnightsAddon.ID, "sallet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType GILDED_GOTHIC = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_gothic"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GILDED_GREENWICH_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_greenwich_armet"), new ResourceLocation(EpicKnightsAddon.ID, "greenwich_armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType GILDED_GREENWICH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gilded_greenwich"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

	public static final ArmorType GREENWICH_ARMET = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "greenwich_armet"), new ResourceLocation(EpicKnightsAddon.ID, "greenwich_armet"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
	public static final ArmorType GREENWICH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "greenwich"), new ResourceLocation("default"), 1.25f, 0.5f, new Integer[] { 230, 315, 335, 275 }, new Integer[] { 2, 5, 8, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");






	public static final ArmorType LANDSKNECHT_ORANGE_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_orange_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_MAGENTA_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_magenta_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_LIGHT_BLUE_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_light_blue_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_YELLOW_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_yellow_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_LIME_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_lime_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_PINK_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_pink_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_GRAY_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_gray_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_LIGHT_GRAY_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_light_gray_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_CYAN_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_cyan_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_PURPLE_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_purple_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_BLUE_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_blue_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_BROWN_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_brown_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_GREEN_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_green_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_RED_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_red_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_BLACK_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_black_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LANDSKNECHT_WHITE_HAT = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_white_hat"), new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_hat"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType ORANGE_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "orange_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType MAGENTA_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "magenta_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LIGHT_BLUE_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "light_blue_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType YELLOW_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "yellow_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LIME_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "lime_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType PINK_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "pink_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType GRAY_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "gray_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType LIGHT_GRAY_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "light_gray_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType CYAN_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "cyan_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType PURPLE_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "purple_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType BLUE_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "blue_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType BROWN_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "brown_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType GREEN_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "green_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType RED_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "red_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType BLACK_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "black_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType WHITE_PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "white_puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(TagKey.create(Registry.ITEM_REGISTRY, new ResourceLocation(EpicKnights.ID, "woolen_fabric"))));
	public static final ArmorType PUFF_AND_SLASH = new ArmorType(new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), new ResourceLocation(EpicKnightsAddon.ID, "puff_and_slash"), 0.0f, 0.0f, new Integer[] { 120, 100, 140, 120 }, new Integer[] { 1, 0, 2, 1 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, () -> Ingredient.of(Items.LEATHER));
}
