package com.magistuarmory.addon.client.render.model;

import com.magistuarmory.addon.EpicKnightsAddon;
import com.magistuarmory.addon.client.render.model.armor.*;
import com.magistuarmory.addon.client.render.model.decoration.*;
import com.magistuarmory.addon.client.render.model.shield.*;
import com.magistuarmory.api.client.render.model.ModModelsProvider;
import com.magistuarmory.client.render.model.decoration.RondelModel;
import com.magistuarmory.client.render.model.decoration.TopDecorationModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.builders.LayerDefinition;

public class AddonModels extends ModModelsProvider
{
	public static AddonModels INSTANCE = new AddonModels(EpicKnightsAddon.ID);

	// Armor
	public static final ModelLayerLocation SALLET_LOCATION = INSTANCE.addArmorModel("sallet", SalletModel::createLayer);
	public static final ModelLayerLocation GREATHELM_LOCATION = INSTANCE.addArmorModel("greathelm", GreathelmModel::createLayer);
	public static final ModelLayerLocation SAVOYARD_HELMET_LOCATION = INSTANCE.addArmorModel("savoyard_helmet", SavoyardHelmetModel::createLayer);
	public static final ModelLayerLocation MORION_LOCATION = INSTANCE.addArmorModel("morion", MorionModel::createLayer);
	public static final ModelLayerLocation MILANESE_ARMET_LOCATION = INSTANCE.addArmorModel("milanese_armet", MilaneseArmetModel::createLayer);
	public static final ModelLayerLocation BRITISH_ARMET_LOCATION = INSTANCE.addArmorModel("british_armet", BritishArmetModel::createLayer);
	public static final ModelLayerLocation VISORED_KETTLEHAT_LOCATION = INSTANCE.addArmorModel("visored_kettlehat", VisoredKettlehatModel::createLayer);
	public static final ModelLayerLocation BICOQUE_LOCATION = INSTANCE.addArmorModel("bicoque", BicoqueModel::createLayer);
	public static final ModelLayerLocation UNDERARMOR_LOCATION = INSTANCE.addArmorModel("underarmor", UnderarmorModel::createLayer);
	public static final ModelLayerLocation SALLET_WITHOUT_NECK_PROTECTION_LOCATION = INSTANCE.addArmorModel("sallet_without_neck_protection", SalletWithoutNeckProtectionModel::createLayer);
	public static final ModelLayerLocation BELLOWS_MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("bellows_maximilian_helmet", BellowsMaximilianHelmetModel::createLayer);
	public static final ModelLayerLocation KULAH_KHUD_LOCATION = INSTANCE.addArmorModel("kulah_khud", KulahKhudModel::createLayer);
	public static final ModelLayerLocation EARLY_GREATHELM_LOCATION = INSTANCE.addArmorModel("early_greathelm", EarlyGreathelmModel::createLayer);
	public static final ModelLayerLocation KLAPPVISOR_BASCINET_LOCATION = INSTANCE.addArmorModel("klappvisor_bascinet", KlappvisorBascinetModel::createLayer);
	public static final ModelLayerLocation LATE_BASCINET_LOCATION = INSTANCE.addArmorModel("late_bascinet", LateBascinetModel::createLayer);
	public static final ModelLayerLocation LOBSTER_TAILED_HELMET_LOCATION = INSTANCE.addArmorModel("lobster_tailed_helmet", LobsterTailedHelmetModel::createLayer);
	public static final ModelLayerLocation CHAPEL_LOCATION = INSTANCE.addArmorModel("chapel", ChapelModel::createLayer);
	public static final ModelLayerLocation LATE_GREATHELM_LOCATION = INSTANCE.addArmorModel("late_greathelm", LateGreathelmModel::createLayer);
	public static final ModelLayerLocation BURGUNDIAN_KETTLEHAT_LOCATION = INSTANCE.addArmorModel("burgundian_kettlehat", BurgundianKettlehatModel::createLayer);
	public static final ModelLayerLocation CLOSED_BURGONET_LOCATION = INSTANCE.addArmorModel("closed_burgonet", ClosedBurgonetModel::createLayer);
	public static final ModelLayerLocation LATE_BURGONET_LOCATION = INSTANCE.addArmorModel("late_burgonet", LateBurgonetModel::createLayer);
	public static final ModelLayerLocation DEVILISH_GROTESQUE_MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("devilish_grotesque_maximilian_helmet", DevilishGrotesqueMaximilianHelmetModel::createLayer);
	public static final ModelLayerLocation FACIAL_GROTESQUE_MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("facial_grotesque_maximilian_helmet", FacialGrotesqueMaximilianHelmetModel::createLayer);
	public static final ModelLayerLocation GREENWICH_ARMET_LOCATION = INSTANCE.addArmorModel("greenwich_armet", GreenwichArmetModel::createLayer);
	public static final ModelLayerLocation LATE_SALLET_LOCATION = INSTANCE.addArmorModel("late_sallet", LateSalletModel::createLayer);
	public static final ModelLayerLocation STEEL_PUFF_AND_SLASH_LOCATION = INSTANCE.addArmorModel("steel_puff_and_slash", SteelPuffAndSlashModel::createLayer);
	public static final ModelLayerLocation STURMHAUBE_LOCATION = INSTANCE.addArmorModel("sturmhaube", SturmhaubeModel::createLayer);
	public static final ModelLayerLocation EXQUISITE_ARMET_LOCATION = INSTANCE.addArmorModel("exquisite_armet", ExquisiteArmetModel::createLayer);
	public static final ModelLayerLocation LANDSKNECHT_HAT_LOCATION = INSTANCE.addArmorModel("landsknecht_hat", LandsknechtHatModel::createLayer);
	public static final ModelLayerLocation PUFF_AND_SLASH_LOCATION = INSTANCE.addArmorModel("puff_and_slash", PuffAndSlashModel::createLayer);
	public static final ModelLayerLocation CONDOTTIERO_CAP_LOCATION = INSTANCE.addArmorModel("condottiero_cap", CondottieroCapModel::createLayer);
	public static final ModelLayerLocation PATRICIAN_TUHER_HELMET_LOCATION = INSTANCE.addArmorModel("patrician_tuher_helmet", PatricianTuherHelmetModel::createLayer);
	public static final ModelLayerLocation LATE_KETTLEHAT_LOCATION = INSTANCE.addArmorModel("late_kettlehat", LateKettlehatModel::createLayer);
	public static final ModelLayerLocation CLOSE_HELMET_LOCATION = INSTANCE.addArmorModel("close_helmet", CloseHelmetModel::createLayer);
	public static final ModelLayerLocation EXQUISITE_MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("exquisite_maximilian_helmet", ExquisiteArmetModel::createLayer);
	public static final ModelLayerLocation CABASSET_LOCATION = INSTANCE.addArmorModel("cabasset", CabassetModel::createLayer);
	public static final ModelLayerLocation EARLY_CABASSET_LOCATION = INSTANCE.addArmorModel("early_cabasset", EarlyCabassetModel::createLayer);
	public static final ModelLayerLocation STRAW_HAT_LOCATION = INSTANCE.addArmorModel("straw_hat", StrawHatModel::createLayer);
	public static final ModelLayerLocation FANCY_HAT_LOCATION = INSTANCE.addArmorModel("fancy_hat", FancyHatModel::createLayer);
	public static final ModelLayerLocation TUNIC_LOCATION = INSTANCE.addArmorModel("tunic", TunicModel::createLayer);
	public static final ModelLayerLocation PARADE_BURGONET_LOCATION = INSTANCE.addArmorModel("parade_burgonet", ParadeBurgonetModel::createLayer);
	public static final ModelLayerLocation NECKLACE_LOCATION = INSTANCE.addArmorModel("necklace", NecklaceArmorModel::createLayer);
	public static final ModelLayerLocation CUMAN_HELMET_LOCATION = INSTANCE.addArmorModel("cuman_helmet", CumanHelmetModel::createLayer);
	public static final ModelLayerLocation FOX_GROTESQUE_MAXIMILIAN_HELMET_LOCATION = INSTANCE.addArmorModel("fox_grotesque_maximilian_helmet", FoxGrotesqueMaximilianHelmetModel::createLayer);
	public static final ModelLayerLocation GRILLED_HELMET_LOCATION = INSTANCE.addArmorModel("grilled_helmet", GrilledHelmetModel::createLayer);
	public static final ModelLayerLocation MAXIMILIAN_BURGONET_LOCATION = INSTANCE.addArmorModel("maximilian_burgonet", MaximilianBurgonetModel::createLayer);
	public static final ModelLayerLocation OPENED_SALLET_LOCATION = INSTANCE.addArmorModel("opened_sallet", OpenedSalletModel::createLayer);
	public static final ModelLayerLocation TILTED_PUFF_AND_SLASH_HAT_LOCATION = INSTANCE.addArmorModel("tilted_puff_and_slash_hat", PuffAndSlashTiltedHatModel::createLayer);
	public static final ModelLayerLocation SALLET_WITHOUT_VISOR_LOCATION = INSTANCE.addArmorModel("sallet_without_visor", SalletWithoutVisorModel::createLayer);
	public static final ModelLayerLocation GERMAN_BASCINET_LOCATION = INSTANCE.addArmorModel("german_bascinet", GermanBascinetModel::createLayer);

	// Decorations
	public static final LayerDefinition SKIRT_MODEL = SkirtModel.createLayer();
	public static final LayerDefinition HELMET_RONDEL_MODEL = HelmetRondelModel.createLayer();
	public static final LayerDefinition HEAVY_SHOULDER_PAD_MODEL = HeavyShoulderPadModel.createLayer();
	public static final LayerDefinition SHOULDER_PADS_MODEL = ShoulderPadsModel.createLayer();
	public static final LayerDefinition RONDEL_MODEL = RondelModel.createLayer();
	public static final LayerDefinition HOOD_MODEL = HoodModel.createLayer();
	public static final LayerDefinition GORGET_MODEL = GorgetModel.createLayer();
	public static final LayerDefinition LANDSKNECHT_HAT_MODEL = LandsknechtHatModel.createLayer();
	public static final LayerDefinition PLACKART_MODEL = PlackartModel.createLayer();
	public static final LayerDefinition PUFF_AND_SLASH_SLEEVES_MODEL = PuffAndSlashSleevesModel.createLayer();
	public static final LayerDefinition CODPIECE_MODEL = CodpieceModel.createLayer();
	public static final LayerDefinition NECKLACE_MODEL = NecklaceModel.createLayer();
	public static final LayerDefinition MEDIEVAL_CLOAK_MODEL = MedievalCloakModel.createLayer();
	public static final LayerDefinition GLOVES_MODEL = GlovesModel.createLayer();


	public static final ModelLayerLocation GOLDEN_PINCE_NEZ_DECORATION_LOCATION = INSTANCE.addDecorationModel("golden_pince_nez", PinceNezModel::createLayer);
	public static final ModelLayerLocation STEEL_MUSTACHE_DECORATION_LOCATION = INSTANCE.addDecorationModel("steel_mustache", MustacheModel::createLayer);
	public static final ModelLayerLocation STEEL_SKIRT_DECORATION_LOCATION = INSTANCE.addDecorationModel("steel_skirt", () -> SKIRT_MODEL);
	public static final ModelLayerLocation GILDED_STEEL_SKIRT_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_steel_skirt", () -> SKIRT_MODEL);
	public static final ModelLayerLocation DARK_STEEL_SKIRT_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_steel_skirt", () -> SKIRT_MODEL);
	public static final ModelLayerLocation GILDED_DARK_STEEL_SKIRT_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_dark_steel_skirt", () -> SKIRT_MODEL);
	public static final ModelLayerLocation HELMET_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("helmet_rondel", () -> HELMET_RONDEL_MODEL);
	public static final ModelLayerLocation GILDED_HELMET_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_helmet_rondel", () -> HELMET_RONDEL_MODEL);
	public static final ModelLayerLocation DARK_HELMET_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_helmet_rondel", () -> HELMET_RONDEL_MODEL);
	public static final ModelLayerLocation GILDED_DARK_HELMET_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_dark_helmet_rondel", () -> HELMET_RONDEL_MODEL);
	public static final ModelLayerLocation DARK_HEAVY_SHOULDER_PAD_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_heavy_shoulder_pad", () -> HEAVY_SHOULDER_PAD_MODEL);
	public static final ModelLayerLocation DARK_SHOULDER_PADS_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_shoulder_pads", () -> SHOULDER_PADS_MODEL);
	public static final ModelLayerLocation GILDED_SHOULDER_PADS_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_shoulder_pads", () -> SHOULDER_PADS_MODEL);
	public static final ModelLayerLocation DARK_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_rondel", () -> RONDEL_MODEL);
	public static final ModelLayerLocation GILDED_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_rondel", () -> RONDEL_MODEL);
	public static final ModelLayerLocation GILDED_DARK_RONDEL_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_dark_rondel", () -> RONDEL_MODEL);
	public static final ModelLayerLocation CHAINMAIL_HOOD_DECORATION_LOCATION = INSTANCE.addDecorationModel("chainmail_hood", () -> HOOD_MODEL);
	public static final ModelLayerLocation SHOULDER_PADS_DECORATION_LOCATION = INSTANCE.addDecorationModel("shoulder_pads", () -> SHOULDER_PADS_MODEL);
	public static final ModelLayerLocation HEAVY_SHOULDER_PAD_DECORATION_LOCATION = INSTANCE.addDecorationModel("heavy_shoulder_pad", () -> HEAVY_SHOULDER_PAD_MODEL);
	public static final ModelLayerLocation GOLDEN_BALL_DECORATION_LOCATION = INSTANCE.addDecorationModel("golden_ball", TopDecorationModel::createLayer);
	public static final ModelLayerLocation GORGET_DECORATION_LOCATION = INSTANCE.addDecorationModel("gorget", () -> GORGET_MODEL);
	public static final ModelLayerLocation ROYAL_PLUME_DECORATION_LOCATION = INSTANCE.addDecorationModel("royal_plume", RoyalPlumeModel::createLayer);
	public static final ModelLayerLocation HORSE_TAIL_DECORATION_LOCATION = INSTANCE.addDecorationModel("horse_tail", HorseTailDecorationModel::createLayer);
	public static final ModelLayerLocation LANDSKNECHT_FEATHERS_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_feathers", LandsknechtFeathersModel::createLayer);
	public static final ModelLayerLocation HANGING_CLOTH_DECORATION_LOCATION = INSTANCE.addDecorationModel("hanging_cloth", HangingClothModel::createLayer);
	public static final ModelLayerLocation UNDERARMOR_TUNIC_DECORATION_LOCATION = INSTANCE.addDecorationModel("underarmor_tunic", UnderarmorTunicModel::createLayer);
	public static final ModelLayerLocation LANDSKNECHT_ORANGE_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_orange_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_MAGENTA_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_magenta_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_LIGHT_BLUE_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_light_blue_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_YELLOW_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_yellow_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_LIME_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_lime_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_PINK_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_pink_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_GRAY_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_gray_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_LIGHT_GRAY_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_light_gray_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_CYAN_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_cyan_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_PURPLE_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_purple_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_BLUE_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_blue_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_BROWN_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_brown_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_GREEN_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_green_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_RED_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_red_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_BLACK_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_black_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation LANDSKNECHT_WHITE_HAT_DECORATION_LOCATION = INSTANCE.addDecorationModel("landsknecht_white_hat", () -> LANDSKNECHT_HAT_MODEL);
	public static final ModelLayerLocation PLACKART_DECORATION_LOCATION = INSTANCE.addDecorationModel("plackart", () -> PLACKART_MODEL);
	public static final ModelLayerLocation GILDED_PLACKART_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_plackart", () -> PLACKART_MODEL);
	public static final ModelLayerLocation DARK_PLACKART_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_plackart", () -> PLACKART_MODEL);
	public static final ModelLayerLocation ARTICULATED_SHOULDER_DEFENSES_DECORATION_LOCATION = INSTANCE.addDecorationModel("articulated_shoulder_defenses", () -> SHOULDER_PADS_MODEL);
	public static final ModelLayerLocation DRAGON_SHOULDER_PADS_DECORATION_LOCATION = INSTANCE.addDecorationModel("dragon_shoulder_pads", () -> SHOULDER_PADS_MODEL);
	public static final ModelLayerLocation GIORNEA_DECORATION_LOCATION = INSTANCE.addDecorationModel("giornea", GiorneaModel::createLayer);
	public static final ModelLayerLocation RAM_HORNS_DECORATION_LOCATION = INSTANCE.addDecorationModel("ram_horns", RamHornsModel::createLayer);
	public static final ModelLayerLocation GOOSE_DECORATION_LOCATION = INSTANCE.addDecorationModel("goose", GooseModel::createLayer);
	public static final ModelLayerLocation ORANGE_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("orange_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation MAGENTA_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("magenta_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation LIGHT_BLUE_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("light_blue_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation YELLOW_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("yellow_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation LIME_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("lime_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation PINK_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("pink_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation GRAY_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("gray_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation LIGHT_GRAY_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("light_gray_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation CYAN_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("cyan_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation PURPLE_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("purple_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation BLUE_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("blue_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation BROWN_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("brown_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation GREEN_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("green_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation RED_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("red_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation BLACK_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("black_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation WHITE_PUFF_AND_SLASH_SLEEVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("white_puff_and_slash_sleeves", () -> PUFF_AND_SLASH_SLEEVES_MODEL);
	public static final ModelLayerLocation DARK_GORGET_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_gorget", () -> GORGET_MODEL);
	public static final ModelLayerLocation GILDED_GORGET_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_gorget", () -> GORGET_MODEL);
	public static final ModelLayerLocation SQUARE_BESAGEWS_DECORATION_LOCATION = INSTANCE.addDecorationModel("square_besagews", () -> RONDEL_MODEL);
	public static final ModelLayerLocation CODPIECE_DECORATION_LOCATION = INSTANCE.addDecorationModel("codpiece", () -> CODPIECE_MODEL);
	public static final ModelLayerLocation GOLDEN_NECKLACE_DECORATION_LOCATION = INSTANCE.addDecorationModel("golden_necklace", () -> NECKLACE_MODEL);
	public static final ModelLayerLocation SILVER_NECKLACE_DECORATION_LOCATION = INSTANCE.addDecorationModel("silver_necklace", () -> NECKLACE_MODEL);
	public static final ModelLayerLocation SILVER_CROSS_NECKLACE_DECORATION_LOCATION = INSTANCE.addDecorationModel("silver_cross_necklace", () -> NECKLACE_MODEL);
	public static final ModelLayerLocation GOLDEN_CROSS_NECKLACE_DECORATION_LOCATION = INSTANCE.addDecorationModel("golden_cross_necklace", () -> NECKLACE_MODEL);
	public static final ModelLayerLocation ARTICULATED_PAULDRONS_DECORATION_LOCATION = INSTANCE.addDecorationModel("articulated_pauldrons", ArticulatedPauldronsModel::createLayer);
	public static final ModelLayerLocation BLACK_CROSS_MEDIEVAL_CLOAK_DECORATION_LOCATION = INSTANCE.addDecorationModel("black_cross_medieval_cloak", () -> MEDIEVAL_CLOAK_MODEL);
	public static final ModelLayerLocation CHAINMAIL_GLOVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("chainmail_gloves", () -> GLOVES_MODEL);
	public static final ModelLayerLocation COMPOSITE_GLOVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("composite_gloves", () -> GLOVES_MODEL);
	public static final ModelLayerLocation GILDED_CHAINMAIL_GLOVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_chainmail_gloves", () -> GLOVES_MODEL);
	public static final ModelLayerLocation GILDED_CHAINMAIL_HOOD_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_chainmail_hood", () -> HOOD_MODEL);
	public static final ModelLayerLocation GILDED_RIVITED_GAUNTLETS_DECORATION_LOCATION = INSTANCE.addDecorationModel("gilded_rivited_gauntlets", () -> GLOVES_MODEL);
	public static final ModelLayerLocation LEATHER_GLOVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("leather_gloves", () -> GLOVES_MODEL);
	public static final ModelLayerLocation MEDIEVAL_CLOAK_DECORATION_LOCATION = INSTANCE.addDecorationModel("medieval_cloak", () -> MEDIEVAL_CLOAK_MODEL);
	public static final ModelLayerLocation PLATED_CHAINMAIL_GLOVES_DECORATION_LOCATION = INSTANCE.addDecorationModel("plated_chainmail_gloves", () -> GLOVES_MODEL);
	public static final ModelLayerLocation PUFF_AND_SLASH_ROBE_DECORATION_LOCATION = INSTANCE.addDecorationModel("puff_and_slash_robe", PuffAndSlashRobeModel::createLayer);
	public static final ModelLayerLocation RED_CROSS_MEDIEVAL_CLOAK_DECORATION_LOCATION = INSTANCE.addDecorationModel("red_cross_medieval_cloak", () -> MEDIEVAL_CLOAK_MODEL);
	public static final ModelLayerLocation RIVITED_GAUNTLETS_DECORATION_LOCATION = INSTANCE.addDecorationModel("rivited_gauntlets", () -> GLOVES_MODEL);
	public static final ModelLayerLocation WHITE_CROSS_MEDIEVAL_CLOAK_DECORATION_LOCATION = INSTANCE.addDecorationModel("white_cross_medieval_cloak", () -> MEDIEVAL_CLOAK_MODEL);
	public static final ModelLayerLocation FRONTAL_FEATHER_DECORATION_LOCATION = INSTANCE.addDecorationModel("frontal_feather", FrontalFeatherModel::createLayer);
	public static final ModelLayerLocation DARK_CODPIECE_DECORATION_LOCATION = INSTANCE.addDecorationModel("dark_codpiece", () -> CODPIECE_MODEL);

	// Shields
	public static final ModelLayerLocation DUELING_SHIELD_MODEL = INSTANCE.addModel("dueling_shield", DuelingShieldModel::createLayer);

	public AddonModels(String modId)
	{
		super(modId);
	}
}