package com.magistuarmory.addon.item;

import com.magistuarmory.addon.EpicKnightsAddon;
import com.magistuarmory.addon.item.armor.AddonArmorTypes;
import com.magistuarmory.api.item.ModItemsProvider;
import com.magistuarmory.item.ArmorDecorationItem;
import com.magistuarmory.item.DyeableArmorDecorationItem;
import com.magistuarmory.item.MedievalWeaponItem;
import com.magistuarmory.item.ModItemTier;
import com.magistuarmory.item.armor.DyeableWearableArmorDecorationItem;
import com.magistuarmory.item.armor.MedievalArmorItem;
import com.magistuarmory.item.armor.MedievalHorseArmorItem;
import com.magistuarmory.misc.ModCreativeTabs;
import dev.architectury.registry.registries.RegistrySupplier;
import me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.annotation.Nullable;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.material.MaterialColor;

public class AddonItems extends ModItemsProvider
{
	public static AddonItems INSTANCE = new AddonItems();

	//Weapons
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_MESSER_SWORD = INSTANCE.addMedievalWeaponItem("steel_messer_sword", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.MESSER_SWORD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_GERMAN_GREATSWORD = INSTANCE.addMedievalWeaponItem("steel_german_greatsword", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.GERMAN_GREATSWORD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_EXECUTIONERS_SWORD = INSTANCE.addMedievalWeaponItem("steel_executioners_sword", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.EXECUTIONERS_SWORD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_LONGSWORD = INSTANCE.addMedievalWeaponItem("steel_longsword", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.LONGSWORD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_ARMING_SWORD_TYPE_XIII = INSTANCE.addMedievalWeaponItem("steel_arming_sword_type_xiii", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.ARMING_SWORD_TYPE_XIII);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_ARMING_SWORD_TYPE_XIV = INSTANCE.addMedievalWeaponItem("steel_arming_sword_type_xiv", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.ARMING_SWORD_TYPE_XIV);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_ARMING_SWORD_TYPE_XV = INSTANCE.addMedievalWeaponItem("steel_arming_sword_type_xv", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.ARMING_SWORD_TYPE_XV);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_RAPIER = INSTANCE.addMedievalWeaponItem("steel_rapier", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.RAPIER);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SIDESWORD = INSTANCE.addMedievalWeaponItem("steel_sidesword", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SIDESWORD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SCIMITAR = INSTANCE.addMedievalWeaponItem("steel_scimitar", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SCIMITAR);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_FALCHION = INSTANCE.addMedievalWeaponItem("steel_falchion", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.FALCHION);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SABRE = INSTANCE.addMedievalWeaponItem("steel_sabre", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SABRE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_DAGGER = INSTANCE.addMedievalWeaponItem("steel_dagger", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.DAGGER);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SICKLE = INSTANCE.addMedievalWeaponItem("steel_sickle", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SICKLE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_BATTLEAXE = INSTANCE.addMedievalWeaponItem("steel_battleaxe", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.BATTLEAXE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_PARTISAN = INSTANCE.addMedievalWeaponItem("steel_partisan", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.PARTISAN);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_BOAR_SPEAR = INSTANCE.addMedievalWeaponItem("steel_boar_spear", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.BOAR_SPEAR);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_GLAIVE = INSTANCE.addMedievalWeaponItem("steel_glaive", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.GLAIVE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_GOEDENDAG = INSTANCE.addMedievalWeaponItem("steel_goedendag", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.GOUDENDAG);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_LANCE = INSTANCE.addLanceItem("steel_lance", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.LANCE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_BILLHOOK = INSTANCE.addMedievalWeaponItem("steel_billhook", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.BILLHOOK);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_FRENCH_HALBERD = INSTANCE.addMedievalWeaponItem("steel_french_halberd", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.FRENCH_HALBERD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_ENGLISH_POLEAXE = INSTANCE.addMedievalWeaponItem("steel_english_poleaxe", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.ENGLISH_POLEAXE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_FAUCHARD = INSTANCE.addMedievalWeaponItem("steel_fauchard", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.FAUCHARD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_ITALIAN_POLEAXE = INSTANCE.addMedievalWeaponItem("steel_italian_poleaxe", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.ITALIAN_POLEAXE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SWISS_HALBERD = INSTANCE.addMedievalWeaponItem("steel_swiss_halberd", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SWISS_HALBERD);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_VOULGE = INSTANCE.addMedievalWeaponItem("steel_voulge", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.VOULGE);
	public static final @Nullable RegistrySupplier<MedievalWeaponItem> STEEL_SCYTHE = INSTANCE.addMedievalWeaponItem("steel_scythe", new Item.Properties().tab(ModCreativeTabs.PARTICULAR_WEAPONS), ModItemTier.STEEL, AddonWeaponTypes.SCYTHE);


	//Armor
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_ARMET = INSTANCE.addKnightItem("dark_knight_helmet", AddonArmorTypes.DARK_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KNIGHT_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_knight_chestplate", AddonArmorTypes.DARK_KNIGHT, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KNIGHT_LEGGINGS = INSTANCE.addMedievalArmorItem("dark_knight_leggings", AddonArmorTypes.DARK_KNIGHT, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KNIGHT_BOOTS = INSTANCE.addMedievalArmorItem("dark_knight_boots", AddonArmorTypes.DARK_KNIGHT, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_STECHHELM = INSTANCE.addJoustingItem("dark_jousting_helmet", AddonArmorTypes.DARK_STECHHELM, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_JOUSTING_CHESTPLATE = INSTANCE.addJoustingItem("dark_jousting_chestplate", AddonArmorTypes.DARK_JOUSTING, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_JOUSTING_LEGGINGS = INSTANCE.addJoustingItem("dark_jousting_leggings", AddonArmorTypes.DARK_JOUSTING, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_JOUSTING_BOOTS = INSTANCE.addJoustingItem("dark_jousting_boots", AddonArmorTypes.DARK_JOUSTING, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_SALLET = INSTANCE.addMedievalArmorItem("dark_gothic_helmet", AddonArmorTypes.DARK_SALLET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GOTHIC_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_gothic_chestplate", AddonArmorTypes.DARK_GOTHIC, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GOTHIC_LEGGINGS = INSTANCE.addMedievalArmorItem("dark_gothic_leggings", AddonArmorTypes.DARK_GOTHIC, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GOTHIC_BOOTS = INSTANCE.addMedievalArmorItem("dark_gothic_boots", AddonArmorTypes.DARK_GOTHIC, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("dark_maximilian_helmet", AddonArmorTypes.DARK_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_MAXIMILIAN_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_maximilian_chestplate", AddonArmorTypes.DARK_MAXIMILIAN, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_MAXIMILIAN_LEGGINGS = INSTANCE.addMedievalArmorItem("dark_maximilian_leggings", AddonArmorTypes.DARK_MAXIMILIAN, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_MAXIMILIAN_BOOTS = INSTANCE.addMedievalArmorItem("dark_maximilian_boots", AddonArmorTypes.DARK_MAXIMILIAN, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GREATHELM = INSTANCE.addMedievalArmorItem("dark_crusader_helmet", AddonArmorTypes.DARK_CRUSADER, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_CRUSADER_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("dark_crusader_chestplate", AddonArmorTypes.DARK_CRUSADER, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), 16777215);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_CRUSADER_LEGGINGS = INSTANCE.addMedievalArmorItem("dark_crusader_leggings", AddonArmorTypes.DARK_CRUSADER, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_CRUSADER_BOOTS = INSTANCE.addDyeableMedievalArmorItem("dark_crusader_boots", AddonArmorTypes.DARK_CRUSADER, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), -3227226);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GRAND_BASCINET = INSTANCE.addMedievalArmorItem("dark_grand_bascinet", AddonArmorTypes.DARK_GRAND_BASCINET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KASTENBRUST_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_kastenbrust_chestplate", AddonArmorTypes.DARK_KASTENBRUST, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KASTENBRUST_LEGGINGS = INSTANCE.addMedievalArmorItem("dark_kastenbrust_leggings", AddonArmorTypes.DARK_KASTENBRUST, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_KASTENBRUST_BOOTS = INSTANCE.addMedievalArmorItem("dark_kastenbrust_boots", AddonArmorTypes.DARK_KASTENBRUST, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SAVOYARD_HELMET = INSTANCE.addMedievalArmorItem("savoyard_helmet", AddonArmorTypes.SAVOYARD_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MORION = INSTANCE.addMedievalArmorItem("morion", AddonArmorTypes.MORION, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PIKEMAN_CHESTPLATE = INSTANCE.addMedievalArmorItem("pikeman_chestplate", AddonArmorTypes.PIKEMAN, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PIKEMAN_BOOTS = INSTANCE.addMedievalArmorItem("pikeman_boots", AddonArmorTypes.PIKEMAN, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> BRITISH_ARMET = INSTANCE.addMedievalArmorItem("british_armet", AddonArmorTypes.BRITISH_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MILANESE_ARMET = INSTANCE.addMedievalArmorItem("milanese_armet", AddonArmorTypes.MILANESE_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> AVANT_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("avant_chestplate", AddonArmorTypes.AVANT, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), 2178191);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> AVANT_LEGGINGS = INSTANCE.addMedievalArmorItem("avant_leggings", AddonArmorTypes.AVANT, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> AVANT_BOOTS = INSTANCE.addDyeableMedievalArmorItem("avant_boots", AddonArmorTypes.AVANT, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), 2178191);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> VISORED_KETTLEHAT = INSTANCE.addMedievalArmorItem("visored_kettlehat", AddonArmorTypes.VISORED_KETTLEHAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> CERVELLIERE = INSTANCE.addMedievalArmorItem("cervelliere", AddonArmorTypes.CERVELLIERE, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> CLOSED_BARBUTE = INSTANCE.addMedievalArmorItem("closed_barbute", AddonArmorTypes.CLOSED_BARBUTE, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> BICOQUE = INSTANCE.addMedievalArmorItem("bicoque", AddonArmorTypes.BICOQUE, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> KULAH_KHUD = INSTANCE.addMedievalArmorItem("kulah_khud", AddonArmorTypes.KULAH_KHUD, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CUMAN_CAPTAIN_HELMET = INSTANCE.addMedievalArmorItem("cuman_captain_helmet", AddonArmorTypes.CUMAN_CAPTAIN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MIRROR_CHESTPLATE = INSTANCE.addMedievalArmorItem("mirror_chestplate", AddonArmorTypes.MIRROR, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MIRROR_BOOTS = INSTANCE.addMedievalArmorItem("mirror_boots", AddonArmorTypes.MIRROR, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SARACEN_HELMET = INSTANCE.addDyeableMedievalArmorItem("saracen_helmet", AddonArmorTypes.SARACEN, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR), MaterialColor.COLOR_RED.col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> SARACEN_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("saracen_chestplate", AddonArmorTypes.SARACEN, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), MaterialColor.COLOR_RED.col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> SARACEN_BOOTS = INSTANCE.addDyeableMedievalArmorItem("saracen_boots", AddonArmorTypes.SARACEN, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), MaterialColor.COLOR_RED.col);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> EARLY_GREATHELM = INSTANCE.addMedievalArmorItem("early_greathelm", AddonArmorTypes.EARLY_GREATHELM, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> XIII_CENTURY_KNIGHT_CHESTPLATE = INSTANCE.addMedievalArmorItem("xiii_century_knight_chestplate", AddonArmorTypes.XIII_CENTURY_KNIGHT, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> XIII_CENTURY_KNIGHT_LEGGINGS = INSTANCE.addMedievalArmorItem("xiii_century_knight_leggings", AddonArmorTypes.XIII_CENTURY_KNIGHT, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> XIII_CENTURY_KNIGHT_BOOTS = INSTANCE.addMedievalArmorItem("xiii_century_knight_boots", AddonArmorTypes.XIII_CENTURY_KNIGHT, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LOBSTER_TAILED_HELMET = INSTANCE.addMedievalArmorItem("lobster_tailed_helmet", AddonArmorTypes.LOBSTER_TAILED_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> ORANGE_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("orange_puff_and_slash_chestplate", AddonArmorTypes.ORANGE_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> ORANGE_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("orange_puff_and_slash_leggings", AddonArmorTypes.ORANGE_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MAGENTA_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("magenta_puff_and_slash_chestplate", AddonArmorTypes.MAGENTA_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> MAGENTA_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("magenta_puff_and_slash_leggings", AddonArmorTypes.MAGENTA_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIGHT_BLUE_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("light_blue_puff_and_slash_chestplate", AddonArmorTypes.LIGHT_BLUE_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIGHT_BLUE_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("light_blue_puff_and_slash_leggings", AddonArmorTypes.LIGHT_BLUE_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> YELLOW_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("yellow_puff_and_slash_chestplate", AddonArmorTypes.YELLOW_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> YELLOW_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("yellow_puff_and_slash_leggings", AddonArmorTypes.YELLOW_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIME_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("lime_puff_and_slash_chestplate", AddonArmorTypes.LIME_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIME_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("lime_puff_and_slash_leggings", AddonArmorTypes.LIME_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PINK_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("pink_puff_and_slash_chestplate", AddonArmorTypes.PINK_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PINK_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("pink_puff_and_slash_leggings", AddonArmorTypes.PINK_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GRAY_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("gray_puff_and_slash_chestplate", AddonArmorTypes.GRAY_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GRAY_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("gray_puff_and_slash_leggings", AddonArmorTypes.GRAY_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIGHT_GRAY_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("light_gray_puff_and_slash_chestplate", AddonArmorTypes.LIGHT_GRAY_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIGHT_GRAY_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("light_gray_puff_and_slash_leggings", AddonArmorTypes.LIGHT_GRAY_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CYAN_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("cyan_puff_and_slash_chestplate", AddonArmorTypes.CYAN_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CYAN_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("cyan_puff_and_slash_leggings", AddonArmorTypes.CYAN_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PURPLE_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("purple_puff_and_slash_chestplate", AddonArmorTypes.PURPLE_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> PURPLE_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("purple_puff_and_slash_leggings", AddonArmorTypes.PURPLE_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BLUE_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("blue_puff_and_slash_chestplate", AddonArmorTypes.BLUE_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BLUE_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("blue_puff_and_slash_leggings", AddonArmorTypes.BLUE_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BROWN_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("brown_puff_and_slash_chestplate", AddonArmorTypes.BROWN_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BROWN_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("brown_puff_and_slash_leggings", AddonArmorTypes.BROWN_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GREEN_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("green_puff_and_slash_chestplate", AddonArmorTypes.GREEN_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GREEN_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("green_puff_and_slash_leggings", AddonArmorTypes.GREEN_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> RED_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("red_puff_and_slash_chestplate", AddonArmorTypes.RED_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> RED_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("red_puff_and_slash_leggings", AddonArmorTypes.RED_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BLACK_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("black_puff_and_slash_chestplate", AddonArmorTypes.BLACK_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> BLACK_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("black_puff_and_slash_leggings", AddonArmorTypes.BLACK_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> WHITE_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("white_puff_and_slash_chestplate", AddonArmorTypes.WHITE_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> WHITE_PUFF_AND_SLASH_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("white_puff_and_slash_leggings", AddonArmorTypes.WHITE_PUFF_AND_SLASH, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> WHITE_UFF_AND_SLASH_BOOTS = INSTANCE.addMedievalArmorItem("puff_and_slash_boots", AddonArmorTypes.PUFF_AND_SLASH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LINEN_COIF = INSTANCE.addDyeableMedievalArmorItem("linen_coif", AddonArmorTypes.LINEN, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.WHITE.getMaterialColor().col);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SALLET_WITHOUT_NECK_PROTECTION = INSTANCE.addMedievalArmorItem("sallet_without_neck_protection", AddonArmorTypes.SALLET_WITHOUT_NECK_PROTECTION, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> BELLOWS_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("bellows_maximilian_helmet", AddonArmorTypes.BELLOWS_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> KLAPPVISOR_BASCINET = INSTANCE.addMedievalArmorItem("klappvisor_bascinet", AddonArmorTypes.KLAPPVISOR_BASCINET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> LATE_BASCINET = INSTANCE.addMedievalArmorItem("late_bascinet", AddonArmorTypes.LATE_BASCINET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));


	public static final @Nullable RegistrySupplier<MedievalArmorItem> CHAPEL = INSTANCE.addDyeableMedievalArmorItem("chapel", AddonArmorTypes.CHAPEL, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR), -4280691);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CHAINED_GAMBESON = INSTANCE.addDyeableMedievalArmorItem("chained_gambeson", AddonArmorTypes.CHAINED_GAMBESON, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), -4280691);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CHAINED_GAMBESON_BOOTS = INSTANCE.addDyeableMedievalArmorItem("chained_gambeson_boots", AddonArmorTypes.CHAINED_GAMBESON, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), -4280691);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> TABLET_HELMET = INSTANCE.addMedievalArmorItem("tablet_helmet", AddonArmorTypes.TABLET_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LATE_GREATHELM = INSTANCE.addMedievalArmorItem("late_greathelm", AddonArmorTypes.LATE_GREATHELM, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> BURGUNDIAN_KETTLEHAT = INSTANCE.addMedievalArmorItem("burgundian_kettlehat", AddonArmorTypes.BURGUNDIAN_KETTLEHAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> CLOSED_BURGONET = INSTANCE.addMedievalArmorItem("closed_burgonet", AddonArmorTypes.CLOSED_BURGONET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LATE_BURGONET = INSTANCE.addMedievalArmorItem("late_burgonet", AddonArmorTypes.LATE_BURGONET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LIGHT_BURGONET = INSTANCE.addMedievalArmorItem("light_burgonet", AddonArmorTypes.LIGHT_BURGONET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DEVILISH_GROTESQUE_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("devilish_grotesque_maximilian_helmet", AddonArmorTypes.DEVILISH_GROTESQUE_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> FACIAL_GROTESQUE_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("facial_grotesque_maximilian_helmet", AddonArmorTypes.FACIAL_GROTESQUE_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GILDED_GREENWICH_ARMET = INSTANCE.addMedievalArmorItem("dark_gilded_greenwich_armet", AddonArmorTypes.DARK_GILDED_GREENWICH_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GILDED_GREENWICH_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_gilded_greenwich_chestplate", AddonArmorTypes.DARK_GILDED_GREENWICH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_GILDED_GREENWICH_BOOTS = INSTANCE.addMedievalArmorItem("dark_gilded_greenwich_boots", AddonArmorTypes.DARK_GILDED_GREENWICH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> LATE_SALLET = INSTANCE.addMedievalArmorItem("late_sallet", AddonArmorTypes.LATE_SALLET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> STEEL_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addMedievalArmorItem("steel_puff_and_slash_chestplate", AddonArmorTypes.STEEL_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> STEEL_PUFF_AND_SLASH_BOOTS = INSTANCE.addMedievalArmorItem("steel_puff_and_slash_boots", AddonArmorTypes.STEEL_PUFF_AND_SLASH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> STURMHAUBE = INSTANCE.addMedievalArmorItem("sturmhaube", AddonArmorTypes.STURMHAUBE, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SILVERED_DARK_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("silvered_dark_maximilian_helmet", AddonArmorTypes.SILVERED_DARK_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> SILVERED_DARK_MAXIMILIAN_CHESTPLATE = INSTANCE.addMedievalArmorItem("silvered_dark_maximilian_chestplate", AddonArmorTypes.SILVERED_DARK_MAXIMILIAN, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> SILVERED_DARK_MAXIMILIAN_BOOTS = INSTANCE.addMedievalArmorItem("silvered_dark_maximilian_boots", AddonArmorTypes.SILVERED_DARK_MAXIMILIAN, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("silvered_dark_bellows_maximilian_helmet", AddonArmorTypes.SILVERED_DARK_BELLOWS_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GRAND_BASCINET = INSTANCE.addMedievalArmorItem("gilded_grand_bascinet", AddonArmorTypes.GILDED_GRAND_BASCINET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CEREMONIAL_KASTENBRUST_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("ceremonial_kastenbrust_chestplate", AddonArmorTypes.CEREMONIAL_KASTENBRUST, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.RED.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> CEREMONIAL_KASTENBRUST_BOOTS = INSTANCE.addDyeableMedievalArmorItem("ceremonial_kastenbrust_boots", AddonArmorTypes.CEREMONIAL_KASTENBRUST, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.RED.getMaterialColor().col);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_STEEL_PUFF_AND_SLASH_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_steel_puff_and_slash_chestplate", AddonArmorTypes.GILDED_STEEL_PUFF_AND_SLASH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_STEEL_PUFF_AND_SLASH_BOOTS = INSTANCE.addMedievalArmorItem("gilded_steel_puff_and_slash_boots", AddonArmorTypes.GILDED_STEEL_PUFF_AND_SLASH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> HEAVY_CUIRASSIER_CHESTPLATE = INSTANCE.addMedievalArmorItem("heavy_cuirassier_chestplate", AddonArmorTypes.HEAVY_CUIRASSIER, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> HEAVY_CUIRASSIER_BOOTS = INSTANCE.addMedievalArmorItem("heavy_cuirassier_boots", AddonArmorTypes.HEAVY_CUIRASSIER, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_HEAVY_CUIRASSIER_CHESTPLATE = INSTANCE.addMedievalArmorItem("dark_heavy_cuirassier_chestplate", AddonArmorTypes.DARK_HEAVY_CUIRASSIER, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> DARK_HEAVY_CUIRASSIER_BOOTS = INSTANCE.addMedievalArmorItem("dark_heavy_cuirassier_boots", AddonArmorTypes.DARK_HEAVY_CUIRASSIER, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_XIV_CENTURY_KNIGHT_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_xivcenturyknight_chestplate", AddonArmorTypes.GILDED_XIV_CENTURY_KNIGHT, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_XIV_CENTURY_KNIGHT_BOOTS = INSTANCE.addMedievalArmorItem("gilded_xivcenturyknight_boots", AddonArmorTypes.GILDED_XIV_CENTURY_KNIGHT, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GALLOWGLASS_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("gallowglass_chestplate", AddonArmorTypes.GALLOWGLASS, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), 0xc4c38c);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GALLOWGLASS_LEGGINGS = INSTANCE.addDyeableMedievalArmorItem("gallowglass_leggings", AddonArmorTypes.GALLOWGLASS, EquipmentSlot.LEGS, new Item.Properties().tab(ModCreativeTabs.ARMOR), 0xc4c38c);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GALLOWGLASS_BOOTS = INSTANCE.addMedievalArmorItem("gallowglass_boots", AddonArmorTypes.GALLOWGLASS, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> ENGLISH_KNIGHT_CHESTPLATE = INSTANCE.addMedievalArmorItem("english_knight_chestplate", AddonArmorTypes.ENGLISH_KNIGHT, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> ENGLISH_KNIGHT_BOOTS = INSTANCE.addMedievalArmorItem("english_knight_boots", AddonArmorTypes.ENGLISH_KNIGHT, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_HALF_ARMOR = INSTANCE.addMedievalArmorItem("gilded_half_armor", AddonArmorTypes.GILDED_HALF_ARMOR, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	//	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("gilded_maximilian_helmet", AddonArmorTypes.GILDED_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_MAXIMILIAN_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_maximilian_chestplate", AddonArmorTypes.GILDED_MAXIMILIAN, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_MAXIMILIAN_BOOTS = INSTANCE.addMedievalArmorItem("gilded_maximilian_boots", AddonArmorTypes.GILDED_MAXIMILIAN, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> COAT_OF_PLATES_CHESTPLATE = INSTANCE.addDyeableMedievalArmorItem("coat_of_plates_chestplate", AddonArmorTypes.COAT_OF_PLATES, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.BROWN.getMaterialColor().col);
	public static final @Nullable RegistrySupplier<MedievalArmorItem> COAT_OF_PLATES_BOOTS = INSTANCE.addDyeableMedievalArmorItem("coat_of_plates_boots", AddonArmorTypes.COAT_OF_PLATES, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR), DyeColor.BROWN.getMaterialColor().col);

	public static final @Nullable RegistrySupplier<MedievalArmorItem> SILVERED_DARK_HALF_ARMOR = INSTANCE.addMedievalArmorItem("silvered_dark_half_armor", AddonArmorTypes.SILVERED_DARK_HALF_ARMOR, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_DARK_SALLET = INSTANCE.addMedievalArmorItem("gilded_dark_sallet", AddonArmorTypes.GILDED_DARK_SALLET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_DARK_GOTHIC_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_dark_gothic_chestplate", AddonArmorTypes.GILDED_DARK_GOTHIC, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_DARK_GOTHIC_BOOTS = INSTANCE.addMedievalArmorItem("gilded_dark_gothic_boots", AddonArmorTypes.GILDED_DARK_GOTHIC, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_SALLET = INSTANCE.addMedievalArmorItem("gilded_sallet", AddonArmorTypes.GILDED_SALLET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GOTHIC_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_gothic_chestplate", AddonArmorTypes.GILDED_GOTHIC, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GOTHIC_BOOTS = INSTANCE.addMedievalArmorItem("gilded_gothic_boots", AddonArmorTypes.GILDED_GOTHIC, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_EXQUISITE_MAXIMILIAN_HELMET = INSTANCE.addMedievalArmorItem("gilded_exquisite_maximilian_helmet", AddonArmorTypes.GILDED_EXQUISITE_MAXIMILIAN_HELMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GREENWICH_ARMET = INSTANCE.addMedievalArmorItem("gilded_greenwich_armet", AddonArmorTypes.GILDED_GREENWICH_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GREENWICH_CHESTPLATE = INSTANCE.addMedievalArmorItem("gilded_greenwich_chestplate", AddonArmorTypes.GILDED_GREENWICH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GILDED_GREENWICH_BOOTS = INSTANCE.addMedievalArmorItem("gilded_greenwich_boots", AddonArmorTypes.GILDED_GREENWICH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));

	public static final @Nullable RegistrySupplier<MedievalArmorItem> GREENWICH_ARMET = INSTANCE.addMedievalArmorItem("greenwich_armet", AddonArmorTypes.GREENWICH_ARMET, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GREENWICH_CHESTPLATE = INSTANCE.addMedievalArmorItem("greenwich_chestplate", AddonArmorTypes.GREENWICH, EquipmentSlot.CHEST, new Item.Properties().tab(ModCreativeTabs.ARMOR));
	public static final @Nullable RegistrySupplier<MedievalArmorItem> GREENWICH_BOOTS = INSTANCE.addMedievalArmorItem("greenwich_boots", AddonArmorTypes.GREENWICH, EquipmentSlot.FEET, new Item.Properties().tab(ModCreativeTabs.ARMOR));






	// Horse Armor
	public static final @Nullable RegistrySupplier<MedievalHorseArmorItem> DARK_BARDING = INSTANCE.items.register("dark_barding", () -> new MedievalHorseArmorItem(12, new ResourceLocation(EpicKnightsAddon.ID, "textures/entity/horse/armor/dark_barding.png"), new Item.Properties().tab(ModCreativeTabs.ARMOR).stacksTo(1)));

	// Decorations
	public static final RegistrySupplier<ArmorDecorationItem> GOLDEN_PINCE_NEZ_DECORATION = INSTANCE.addArmorDecorationItem("golden_pince_nez_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "golden_pince_nez"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> STEEL_MUSTACHE_DECORATION = INSTANCE.addArmorDecorationItem("steel_mustache_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "steel_mustache"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> STEEL_SKIRT_DECORATION = INSTANCE.addArmorDecorationItem("steel_skirt_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "steel_skirt"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_STEEL_SKIRT_DECORATION = INSTANCE.addArmorDecorationItem("gilded_steel_skirt_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_steel_skirt"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> DARK_STEEL_SKIRT_DECORATION = INSTANCE.addArmorDecorationItem("dark_steel_skirt_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "dark_steel_skirt"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_DARK_STEEL_SKIRT_DECORATION = INSTANCE.addArmorDecorationItem("gilded_dark_steel_skirt_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_steel_skirt"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> HELMET_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("helmet_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "helmet_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_HELMET_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("gilded_helmet_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_helmet_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> DARK_HELMET_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("dark_helmet_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "dark_helmet_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_DARK_HELMET_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("gilded_dark_helmet_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_helmet_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> DARK_HEAVY_SHOULDER_PAD_DECORATION = INSTANCE.addArmorDecorationItem("dark_heavy_shoulder_pad_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "dark_heavy_shoulder_pad"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> DARK_SHOULDER_PADS_DECORATION = INSTANCE.addArmorDecorationItem("dark_shoulder_pads_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "dark_shoulder_pads"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_SHOULDER_PADS_DECORATION = INSTANCE.addArmorDecorationItem("gilded_shoulder_pads_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_shoulder_pads"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> DARK_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("dark_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "dark_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("gilded_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GILDED_DARK_RONDEL_DECORATION = INSTANCE.addArmorDecorationItem("gilded_dark_rondel_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gilded_dark_rondel"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GOLDEN_NECKLACE_DECORATION = INSTANCE.addArmorDecorationItem("golden_necklace_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "golden_necklace"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> CHAINMAIL_HOOD_DECORATION = INSTANCE.addArmorDecorationItem("chainmail_hood_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "chainmail_hood"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> SHOULDER_PADS_DECORATION = INSTANCE.addArmorDecorationItem("shoulder_pads_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "shoulder_pads"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> HEAVY_SHOULDER_PAD_DECORATION = INSTANCE.addArmorDecorationItem("heavy_shoulder_pad_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "heavy_shoulder_pad"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<ArmorDecorationItem> GOLDEN_BALL_DECORATION = INSTANCE.addArmorDecorationItem("golden_ball_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "golden_ball"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD));
	public static final RegistrySupplier<ArmorDecorationItem> GORGET_DECORATION = INSTANCE.addArmorDecorationItem("gorget_decoration", () -> new ArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "gorget"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST));
	public static final RegistrySupplier<DyeableArmorDecorationItem> ROYAL_PLUME_DECORATION = INSTANCE.addDyeableArmorDecorationItem("royal_plume_decoration", () -> new DyeableArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "royal_plume"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD, DyeColor.WHITE.getMaterialColor().col));
	public static final RegistrySupplier<DyeableArmorDecorationItem> HORSE_TAIL_DECORATION = INSTANCE.addDyeableArmorDecorationItem("horse_tail_decoration", () -> new DyeableArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "horse_tail"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD, DyeColor.RED.getMaterialColor().col));
	public static final RegistrySupplier<DyeableArmorDecorationItem> LANDSKNECHT_FEATHERS_DECORATION = INSTANCE.addDyeableArmorDecorationItem("landsknecht_feathers_decoration", () -> new DyeableArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "landsknecht_feathers"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.HEAD, DyeColor.WHITE.getMaterialColor().col));
	public static final RegistrySupplier<DyeableArmorDecorationItem> HANGING_CLOTH_DECORATION = INSTANCE.addDyeableArmorDecorationItem("hanging_cloth_decoration", () -> new DyeableArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "hanging_cloth"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST, DyeColor.RED.getMaterialColor().col));
	public static final RegistrySupplier<DyeableArmorDecorationItem> UNDERARMOR_TUNIC_DECORATION = INSTANCE.addDyeableArmorDecorationItem("underarmor_tunic_decoration", () -> new DyeableArmorDecorationItem(new ResourceLocation(EpicKnightsAddon.ID, "underarmor_tunic"), new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), EquipmentSlot.CHEST, DyeColor.RED.getMaterialColor().col));
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> ORANGE_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("orange_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_ORANGE_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> MAGENTA_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("magenta_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_MAGENTA_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> LIGHT_BLUE_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("light_blue_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_LIGHT_BLUE_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> YELLOW_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("yellow_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_YELLOW_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> LIME_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("lime_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_LIME_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> PINK_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("pink_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_PINK_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> GRAY_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("gray_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_GRAY_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> LIGHT_GRAY_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("light_gray_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_LIGHT_GRAY_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> CYAN_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("cyan_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_CYAN_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> PURPLE_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("purple_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_PURPLE_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> BLUE_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("blue_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_BLUE_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> BROWN_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("brown_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_BROWN_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> GREEN_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("green_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_GREEN_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> RED_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("red_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_RED_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> BLACK_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("black_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_BLACK_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);
	public static final RegistrySupplier<DyeableWearableArmorDecorationItem> WHITE_LANDSKNECHT_HAT_DECORATION = INSTANCE.addDyeableWearableArmorDecorationItem("white_landsknecht_hat_decoration", AddonArmorTypes.LANDSKNECHT_WHITE_HAT, EquipmentSlot.HEAD, new Item.Properties().tab(ModCreativeTabs.ARMOR_DECORATIONS), DyeColor.WHITE.getMaterialColor().col);

	public AddonItems()
	{
		super(EpicKnightsAddon.ID);
	}
}
